## （１）国土数値情報 駅別乗降客数データ (S12-25)

In [1]:
import zipfile
from pathlib import Path

import pandas as pd
import geopandas as gpd

pd.set_option("display.max_columns", None)

# このノートブックは script/ に置かれている想定。リポジトリ直下を基準にする。
BASE_DIR = Path.cwd().parent if Path.cwd().name == "script" else Path.cwd()
ZIP_PATH = BASE_DIR / "data" / "駅別乗降客数データ" / "S12-25_GML.zip"
assert ZIP_PATH.exists(), f"ZIP が見つかりません: {ZIP_PATH}"

In [2]:
# ZIP 内のファイル一覧を確認
with zipfile.ZipFile(ZIP_PATH) as zf:
    for name in zf.namelist():
        print(name)

S12-25_GML/
S12-25_GML/KS-META-S12-25.xml
S12-25_GML/KsjAppSchema-S12-v3_3.xsd
S12-25_GML/Shift-JIS/
S12-25_GML/Shift-JIS/S12-25.xml
S12-25_GML/Shift-JIS/S12-25_NumberOfPassengers.dbf
S12-25_GML/Shift-JIS/S12-25_NumberOfPassengers.geojson
S12-25_GML/Shift-JIS/S12-25_NumberOfPassengers.prj
S12-25_GML/Shift-JIS/S12-25_NumberOfPassengers.shp
S12-25_GML/Shift-JIS/S12-25_NumberOfPassengers.shx
S12-25_GML/UTF-8/
S12-25_GML/UTF-8/S12-25.xml
S12-25_GML/UTF-8/S12-25_NumberOfPassengers.dbf
S12-25_GML/UTF-8/S12-25_NumberOfPassengers.geojson
S12-25_GML/UTF-8/S12-25_NumberOfPassengers.prj
S12-25_GML/UTF-8/S12-25_NumberOfPassengers.shp
S12-25_GML/UTF-8/S12-25_NumberOfPassengers.shx

In [3]:
# ZIP を解凍せず、geopandas の zip:// 仮想パスで直接 GeoJSON を読み込む
GEOJSON_INNER = "S12-25_GML/UTF-8/S12-25_NumberOfPassengers.geojson"
read_path = f"zip://{ZIP_PATH}!{GEOJSON_INNER}"

gdf = gpd.read_file(read_path)
print("行数 x 列数:", gdf.shape)
print("CRS:", gdf.crs)

行数 x 列数: (10534, 64)
CRS: EPSG:6668

In [4]:
# 属性列を S12 仕様の日本語名にリネーム
# 固定項目
rename_map = {
    "S12_001": "駅名",
    "S12_001c": "駅コード",
    "S12_001g": "グループコード",
    "S12_002": "運営会社",
    "S12_003": "路線名",
    "S12_004": "鉄道区分",
    "S12_005": "事業者種別",
}

# 年度ごとに [重複コード, データ有無コード, 備考, 乗降客数] が4列ずつ繰り返す
# 2011年度=S12_006〜S12_009 ... 2024年度=S12_058〜S12_061
for i, year in enumerate(range(2011, 2025)):
    base = 6 + i * 4
    rename_map[f"S12_{base:03d}"] = f"重複コード{year}"
    rename_map[f"S12_{base + 1:03d}"] = f"データ有無コード{year}"
    rename_map[f"S12_{base + 2:03d}"] = f"備考{year}"
    rename_map[f"S12_{base + 3:03d}"] = f"乗降客数{year}"

gdf = gdf.rename(columns=rename_map)
list(gdf.columns)

['駅名',
 '駅コード',
 'グループコード',
 '運営会社',
 '路線名',
 '鉄道区分',
 '事業者種別',
 '重複コード2011',
 'データ有無コード2011',
 '備考2011',
 '乗降客数2011',
 '重複コード2012',
 'データ有無コード2012',
 '備考2012',
 '乗降客数2012',
 '重複コード2013',
 'データ有無コード2013',
 '備考2013',
 '乗降客数2013',
 '重複コード2014',
 'データ有無コード2014',
 '備考2014',
 '乗降客数2014',
 '重複コード2015',
 'データ有無コード2015',
 '備考2015',
 '乗降客数2015',
 '重複コード2016',
 'データ有無コード2016',
 '備考2016',
 '乗降客数2016',
 '重複コード2017',
 'データ有無コード2017',
 '備考2017',
 '乗降客数2017',
 '重複コード2018',
 'データ有無コード2018',
 '備考2018',
 '乗降客数2018',
 '重複コード2019',
 'データ有無コード2019',
 '備考2019',
 '乗降客数2019',
 '重複コード2020',
 'データ有無コード2020',
 '備考2020',
 '乗降客数2020',
 '重複コード2021',
 'データ有無コード2021',
 '備考2021',
 '乗降客数2021',
 '重複コード2022',
 'データ有無コード2022',
 '備考2022',
 '乗降客数2022',
 '重複コード2023',
 'データ有無コード2023',
 '備考2023',
 '乗降客数2023',
 '重複コード2024',
 'データ有無コード2024',
 '備考2024',
 '乗降客数2024',
 'geometry']

In [5]:
gdf.info()
gdf.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 10534 entries, 0 to 10533
Data columns (total 64 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   駅名            10534 non-null  object
 1   駅コード          10297 non-null  object
 2   グループコード       10297 non-null  object
 3   運営会社          10534 non-null  object
 4   路線名           10534 non-null  object
 5   鉄道区分          10534 non-null  int32
 6   事業者種別         10534 non-null  int32
 7   重複コード2011     10534 non-null  int32
 8   データ有無コード2011  10534 non-null  int32
 9   備考2011        122 non-null    object
 10  乗降客数2011      10534 non-null  int32
 11  重複コード2012     10534 non-null  int32
 12  データ有無コード2012  10534 non-null  int32
 13  備考2012        144 non-null    object
 14  乗降客数2012      10534 non-null  int32
 15  重複コード2013     10534 non-null  int32
 16  データ有無コード2013  10534 non-null  int32
 17  備考2013        159 non-null    object
 18  乗降客数2013      10534 non-null  int32
 19  重複コード2014     10534 non-null  int32
 20  データ有無コード2014  10534 non-null  int32
 21  備考2014        293 non-null    object
 22  乗降客数2014      10534 non-null  int32
 23  重複コード2015     10534 non-null  int32
 24  データ有無コード2015  10534 non-null  int32
 25  備考2015        139 non-null    object
 26  乗降客数2015      10534 non-null  int32
 27  重複コード2016     10534 non-null  int32
 28  データ有無コード2016  10534 non-null  int32
 29  備考2016        110 non-null    object
 30  乗降客数2016      10534 non-null  int32
 31  重複コード2017     10534 non-null  int32
 32  データ有無コード2017  10534 non-null  int32
 33  備考2017        85 non-null     object
 34  乗降客数2017      10534 non-null  int32
 35  重複コード2018     10534 non-null  int32
 36  データ有無コード2018  10534 non-null  int32
 37  備考2018        261 non-null    object
 38  乗降客数2018      10534 non-null  int32
 39  重複コード2019     10534 non-null  int32
 40  データ有無コード2019  10534 non-null  int32
 41  備考2019        208 non-null    object
 42  乗降客数2019      10534 non-null  int32
 43  重複コード2020     10534 non-null  int32
 44  データ有無コード2020  10534 non-null  int32
 45  備考2020        273 non-null    object
 46  乗降客数2020      10534 non-null  int32
 47  重複コード2021     10534 non-null  int32
 48  データ有無コード2021  10534 non-null  int32
 49  備考2021        182 non-null    object
 50  乗降客数2021      10534 non-null  int32
 51  重複コード2022     10534 non-null  int32
 52  データ有無コード2022  10534 non-null  int32
 53  備考2022        566 non-null    object
 54  乗降客数2022      10534 non-null  int32
 55  重複コード2023     10534 non-null  int32
 56  データ有無コード2023  10534 non-null  int32
 57  備考2023        613 non-null    object
 58  乗降客数2023      10534 non-null  int32
 59  重複コード2024     10534 non-null  int32
 60  データ有無コード2024  10534 non-null  int32
 61  備考2024        633 non-null    object
 62  乗降客数2024      10534 non-null  int32
 63  geometry      10534 non-null  geometry
dtypes: geometry(1), int32(44), object(19)
memory usage: 3.4+ MB

,駅名,駅コード,グループコード,運営会社,路線名,鉄道区分,事業者種別,重複コード2011,データ有無コード2011,備考2011,乗降客数2011,重複コード2012,データ有無コード2012,備考2012,乗降客数2012,重複コード2013,データ有無コード2013,備考2013,乗降客数2013,重複コード2014,データ有無コード2014,備考2014,乗降客数2014,重複コード2015,データ有無コード2015,備考2015,乗降客数2015,重複コード2016,データ有無コード2016,備考2016,乗降客数2016,重複コード2017,データ有無コード2017,備考2017,乗降客数2017,重複コード2018,データ有無コード2018,備考2018,乗降客数2018,重複コード2019,データ有無コード2019,備考2019,乗降客数2019,重複コード2020,データ有無コード2020,備考2020,乗降客数2020,重複コード2021,データ有無コード2021,備考2021,乗降客数2021,重複コード2022,データ有無コード2022,備考2022,乗降客数2022,重複コード2023,データ有無コード2023,備考2023,乗降客数2023,重複コード2024,データ有無コード2024,備考2024,乗降客数2024,geometry
0,二月田,010112,010112,九州旅客鉄道,指宿枕崎線,11,2,1,3,None,0,1,3,None,0,1,3,None,0,1,3,None,0,1,3,None,0,1,3,None,0,1,3,None,0,1,1,None,658,1,1,None,690,1,1,None,318,1,1,None,305,1,1,None,622,1,1,None,664,1,1,None,726,"LINESTRING (130.63035 31.25405, 130.62985 31.2..."
1,古島,010127,010127,沖縄都市モノレール,沖縄都市モノレール線,23,5,1,1,None,3907,1,1,None,3980,1,1,None,4572,1,1,None,4187,1,1,None,4648,1,1,None,4528,1,1,None,4819,1,1,None,5086,1,1,None,5143,1,1,None,3404,1,1,None,3534,1,1,None,4401,1,1,None,4903,1,1,None,5490,"LINESTRING (127.70279 26.23035, 127.70309 26.2..."
2,お台場海浜公園,004091,004091,ゆりかもめ,東京臨海新交通臨海線,24,5,1,1,None,14612,1,1,None,16130,1,1,None,16357,1,1,None,16515,1,1,None,17537,1,1,None,17488,1,1,None,16944,1,1,None,17165,1,1,None,16899,1,1,None,7703,1,1,None,8535,1,1,None,11171,1,1,None,13195,1,1,None,13435,"LINESTRING (139.77818 35.62961, 139.77888 35.63)"
3,東京国際クルーズターミナル,004128,004128,ゆりかもめ,東京臨海新交通臨海線,24,5,1,1,None,3767,1,1,None,3235,1,1,None,3407,1,1,None,3782,1,1,None,3682,1,1,None,3682,1,1,None,3590,1,1,None,3551,1,1,None,3191,1,1,None,1383,1,1,None,1984,1,1,None,2300,1,1,None,2963,1,1,None,3503,"LINESTRING (139.77333 35.62109, 139.77288 35.6..."
4,テレコムセンター,004144,004144,ゆりかもめ,東京臨海新交通臨海線,24,5,1,1,None,12112,1,1,None,12775,1,1,None,13366,1,1,None,14138,1,1,None,14069,1,1,None,14069,1,1,None,13744,1,1,None,13475,1,1,None,12140,1,1,None,6536,1,1,None,7631,1,1,None,8118,1,1,None,8505,1,1,None,9267,"LINESTRING (139.78001 35.61791, 139.77932 35.6..."

## （２）駅グループ単位への集約

`docs/passenger_aggregation.md` の設計に基づき、**駅名 + 半径1km** で駅をまとめ、
レベル時系列（各年の乗降客数）と増減率（パターン1・2）を生成する。

- 在/欠測の判定: `データ有無コード==1` を実測（値0も実測の0）、それ以外は欠測（0扱いしない）
- 構成単位: 運営会社（路線は事業者内で合算。重複行は0なので二重計上なし）
- 出力ファイル（最終セル）: メイン **`station_dataset.csv`**（1群1行・人口等を統合）＋ 監査明細 **`station_operator_detail.csv`**（1群×1社）。日本語の列【名】は出力時にASCIIへ（`駅名→station_name`, `都道府県→prefecture`, `運営会社→operator`／値は日本語のまま）

In [6]:
# 集約のための定数と前処理
import numpy as np
from sklearn.cluster import DBSCAN

YEARS = list(range(2011, 2025))
PRE_WINDOW  = [2017, 2018, 2019]   # コロナ前の参照窓（平常年は代替可能）
POST_WINDOW = [2023, 2024]         # コロナ後（回復期）の参照窓。2022以前は底値なので不可

# 乗降客数列を数値化（在/欠測の判定は「データ有無コード」で行うため、ここは数値化のみ）
for y in YEARS:
    gdf[f"乗降客数{y}"] = pd.to_numeric(gdf[f"乗降客数{y}"], errors="coerce")

In [7]:
# 空間グループ: 代表点を取り、駅名ごとに haversine DBSCAN(eps=1km) でクラスタリング
_pt = gdf.geometry.representative_point()
gdf["lon"] = _pt.x
gdf["lat"] = _pt.y

EARTH_R = 6_371_000.0          # 地球半径[m]
EPS     = 1000 / EARTH_R       # 半径1km を弧度に換算

grp = pd.Series(index=gdf.index, dtype=object)
for name, sub_idx in gdf.groupby("駅名").groups.items():
    sub_idx = list(sub_idx)
    if len(sub_idx) == 1:                       # 単独駅はクラスタリング不要
        grp.loc[sub_idx[0]] = f"{name}#0"
        continue
    coords = np.radians(gdf.loc[sub_idx, ["lat", "lon"]].to_numpy())
    lab = DBSCAN(eps=EPS, min_samples=1, metric="haversine").fit(coords).labels_
    for j, l in zip(sub_idx, lab):
        grp.loc[j] = f"{name}#{l}"
gdf["grp"] = grp   # 例: "東京#0"（駅名を内包。同名遠方駅は #1, #2 ... に分かれる）

print("駅グループ数:", gdf["grp"].nunique(), " / 元の行数:", len(gdf))

駅グループ数: 9273  / 元の行数: 10534

In [8]:
# (grp, 運営会社, 年) に集約 → 運営会社×年 のワイド表（present / pax）
_rows = []
for y in YEARS:
    g = (gdf.groupby(["grp", "運営会社"])
            .agg(present=(f"データ有無コード{y}", lambda s: bool((s == 1).any())),
                 pax=(f"乗降客数{y}", "sum"))                  # 重複行は0なので二重計上なし
            .reset_index())
    g["year"] = y
    _rows.append(g)
op_year = pd.concat(_rows, ignore_index=True)

pres = (op_year.pivot_table(index=["grp", "運営会社"], columns="year",
                            values="present", aggfunc="first").fillna(False)[YEARS])
paxw = (op_year.pivot_table(index=["grp", "運営会社"], columns="year",
                            values="pax", aggfunc="first").fillna(0.0)[YEARS])
print("運営会社×群:", len(pres))

運営会社×群: 9781

### 指標① レベル時系列（inclusive・補間なし）

その年に実測のある全社を合算。欠測は0扱いせず、全社欠測の年は NaN（グラフは線を切る）。
社が抜けた年は寄与社数 `n_op` が下がるので、谷が「データ穴」か「実減」か判別できる。

In [9]:
# 各年の合算（在の社のみ）と、群の延べ社数・構成一定フラグ
present_long = op_year[op_year["present"]]

level = (present_long.groupby(["grp", "year"])
         .agg(pax=("pax", "sum"))
         .reset_index())
pax_wide = level.pivot(index="grp", columns="year", values="pax").reindex(columns=YEARS)
pax_wide.columns = [f"pax_{y}" for y in YEARS]   # 欠測年は自然に NaN

# 群の延べ運営会社数
n_op = pres.reset_index().groupby("grp")["運営会社"].nunique()

# level_complete: 構成が全データ年で一定か
#   = 群に現れる全社が、群がデータを持つ全年で在 であること
op_present_years = present_long.groupby(["grp", "運営会社"])["year"].nunique()
grp_data_years   = present_long.groupby("grp")["year"].nunique()
min_op_years     = op_present_years.groupby("grp").min()
level_complete   = (min_op_years == grp_data_years.reindex(min_op_years.index))

print("構成一定の群:", int(level_complete.sum()), "/", len(level_complete))

構成一定の群: 8434 / 8598

### 指標② パターン1（直近 2024/2023）

2023・2024の両方で実測があり、2023値>0 の社だけを basket に合算して比率を取る。

In [10]:
# パターン1: rate_yoy と異常値フラグ
m1 = pres[2023] & pres[2024] & (paxw[2023] > 0)
d1 = paxw.loc[m1, 2023].groupby(level="grp").sum()
n1 = paxw.loc[m1, 2024].groupby(level="grp").sum()
rate_yoy = (n1 / d1 - 1.0)
rate_yoy = rate_yoy[d1 > 0]
flag_yoy = rate_yoy.abs() > 0.30          # 事業者内の報告基準変更などを検出

print("パターン1 算出可能:", len(rate_yoy), "群  中央値: {:+.2f}%".format(rate_yoy.median()*100))

パターン1 算出可能: 7367 群  中央値: +2.14%

### 指標③ パターン2（コロナ前→後・事業者単位）

各社について「pre窓(2017-19)の最新実測」→「post窓(2023-24)の最新実測」を取り、
両方そろう社だけを basket に合算。参照年は社ごとに異なってよい（各社は自分基準で like-for-like）。

In [11]:
# パターン2: rate_covid と信頼性フラグ
def _latest(years_win):
    """各(grp,運営会社)について、窓内で present かつ pax>0 の最新年と値を返す"""
    yr  = pd.Series(np.nan, index=pres.index)
    val = pd.Series(0.0,    index=pres.index)
    for y in years_win:                       # 昇順に上書き → 最大年が残る
        ok  = pres[y] & (paxw[y] > 0)
        yr  = yr.mask(ok, y)
        val = val.mask(ok, paxw[y])
    return yr, val

pre_year,  pre_val  = _latest(PRE_WINDOW)
post_year, post_val = _latest(POST_WINDOW)

basket2 = pre_year.notna() & post_year.notna()           # pre/post 両方ある社のみ（pre/post一貫）
d2 = pre_val[basket2].groupby(level="grp").sum()
n2 = post_val[basket2].groupby(level="grp").sum()
rate_covid = (n2 / d2 - 1.0)
rate_covid = rate_covid[d2 > 0]

# 品質: 被覆率(basket社数/延べ社数) と pre年の最古
n_basket  = basket2.groupby(level="grp").sum()
cov_covid = n_basket / n_op.reindex(n_basket.index)
min_pre   = pre_year[basket2].groupby(level="grp").min()
flag_covid = (((cov_covid < 1.0) | (min_pre < 2019)).reindex(rate_covid.index, fill_value=True)
              | (rate_covid.abs() > 1.0))   # 極端値(|率|>100%)も要注意（小駅の分母ノイズ等。rate_yoyと設計統一）

# 除外用の低分母フラグ（docs/260731_reliability_flag_semantics.md）。
# flag_covid は「被覆<100% / pre<2019 / |率|>100%」の OR で、**除外に使うべき条件（低分母）と
# 注意喚起で足りる条件（被覆・参照年）が混ざっている**。そのままだと新宿・横浜のような大駅が
# 「低分母」の名目で消えるため、値そのものが信用できない |率|>100% だけを別列に切り出す。
flag_covid_lown = rate_covid.abs() > 1.0

print("パターン2 算出可能:", len(rate_covid), "群  中央値: {:+.2f}%".format(rate_covid.median()*100))
print("  flag_covid(注意) :", int(flag_covid.sum()), "群 /  flag_covid_lown(除外):", int(flag_covid_lown.sum()), "群")

パターン2 算出可能: 7684 群  中央値: -8.40%
  flag_covid(注意) : 238 群 /  flag_covid_lown(除外): 85 群

### メイン / 監査用テーブルの組み立て

In [12]:
# メイン station_group（1群1行）。今後 人口・地価などはこの右に追記していく
ident = gdf.groupby("grp").agg(駅名=("駅名", "first"), lon=("lon", "mean"), lat=("lat", "mean"))

station_group = ident.join(pax_wide)
station_group["n_op"]           = n_op.reindex(station_group.index)
station_group["level_complete"] = level_complete.reindex(station_group.index, fill_value=True)
station_group["rate_yoy"]       = (rate_yoy * 100).round(1).reindex(station_group.index)
station_group["flag_yoy"]       = flag_yoy.reindex(station_group.index, fill_value=False).astype("int8")
station_group["rate_covid"]     = (rate_covid * 100).round(1).reindex(station_group.index)
station_group["flag_covid"]     = flag_covid.reindex(station_group.index, fill_value=False).astype("int8")
station_group["flag_covid_lown"] = flag_covid_lown.reindex(station_group.index, fill_value=False).astype("int8")

for y in YEARS:                                   # NaN許容整数に
    station_group[f"pax_{y}"] = station_group[f"pax_{y}"].round().astype("Int64")
station_group = station_group.reset_index()

print("station_group:", station_group.shape)
station_group.head()

station_group: (9273, 25)

,grp,駅名,lon,lat,pax_2011,pax_2012,pax_2013,pax_2014,pax_2015,pax_2016,pax_2017,pax_2018,pax_2019,pax_2020,pax_2021,pax_2022,pax_2023,pax_2024,n_op,level_complete,rate_yoy,flag_yoy,rate_covid,flag_covid,flag_covid_lown
0,JA広島病院前#0,JA広島病院前,132.32251,34.34405,3403,3403,3403,3403,3403,3403,1674,1548,1474,1153,1085,1178,1270,1474,1,True,16.1,0,0.0,0,0
1,JR三山木#0,JR三山木,135.78427,34.79899,1484,1586,1613,1676,1800,1866,1899,2004,2138,1626,1678,1762,1924,2052,1,True,6.7,0,-4.0,0,0
2,JR五位堂#0,JR五位堂,135.71831,34.52768,1521,1493,1448,1444,1484,1526,1567,1576,1514,1246,1314,1364,1436,1424,1,True,-0.8,0,-5.9,0,0
3,JR俊徳道#0,JR俊徳道,135.57249,34.65830,6471,6899,7347,7512,7802,7948,8147,8394,10402,8108,9494,11170,12180,13006,1,True,6.8,0,25.0,0,0
4,JR小倉#0,JR小倉,135.78634,34.88913,3817,3828,3871,3816,3844,3724,3752,3734,3700,2828,2944,3282,3632,3992,1,True,9.9,0,7.9,0,0

In [13]:
# 監査用 station_group_operator（1群×1社）。各年値・在/欠測・参照年を保持
_pax = paxw.where(pres, np.nan)                    # 欠測は NaN（実測の0と区別）
_pax.columns  = [f"pax_{y}" for y in YEARS]
_present = pres.copy()
_present.columns = [f"present_{y}" for y in YEARS]

station_group_operator = _pax.join(_present)
station_group_operator["pre_year"]  = pre_year
station_group_operator["post_year"] = post_year
for y in YEARS:
    station_group_operator[f"pax_{y}"] = station_group_operator[f"pax_{y}"].round().astype("Int64")
station_group_operator = station_group_operator.reset_index()

# 事業者名を station_group に畳み込む（pax 規模の降順で『・』連結・カード表示用の単一文字列）
_ops = (station_group_operator
        .sort_values(["grp", "pax_2024"], ascending=[True, False])
        .groupby("grp", sort=True)["運営会社"]
        .agg(lambda s: "・".join(s.dropna().astype(str))))
station_group["operators"] = station_group["grp"].map(_ops)

print("station_group_operator:", station_group_operator.shape)
station_group_operator.head()

station_group_operator: (9781, 32)

,grp,運営会社,pax_2011,pax_2012,pax_2013,pax_2014,pax_2015,pax_2016,pax_2017,pax_2018,pax_2019,pax_2020,pax_2021,pax_2022,pax_2023,pax_2024,present_2011,present_2012,present_2013,present_2014,present_2015,present_2016,present_2017,present_2018,present_2019,present_2020,present_2021,present_2022,present_2023,present_2024,pre_year,post_year
0,JA広島病院前#0,広島電鉄,3403,3403,3403,3403,3403,3403,1674,1548,1474,1153,1085,1178,1270,1474,True,True,True,True,True,True,True,True,True,True,True,True,True,True,2019.0,2024.0
1,JR三山木#0,西日本旅客鉄道,1484,1586,1613,1676,1800,1866,1899,2004,2138,1626,1678,1762,1924,2052,True,True,True,True,True,True,True,True,True,True,True,True,True,True,2019.0,2024.0
2,JR五位堂#0,西日本旅客鉄道,1521,1493,1448,1444,1484,1526,1567,1576,1514,1246,1314,1364,1436,1424,True,True,True,True,True,True,True,True,True,True,True,True,True,True,2019.0,2024.0
3,JR俊徳道#0,西日本旅客鉄道,6471,6899,7347,7512,7802,7948,8147,8394,10402,8108,9494,11170,12180,13006,True,True,True,True,True,True,True,True,True,True,True,True,True,True,2019.0,2024.0
4,JR小倉#0,西日本旅客鉄道,3817,3828,3871,3816,3844,3724,3752,3734,3700,2828,2944,3282,3632,3992,True,True,True,True,True,True,True,True,True,True,True,True,True,True,2019.0,2024.0

## （３）都道府県・駅名表記・検索名表記

国土数値情報「行政区域(N03)」の都道府県ポリゴンを群の代表点に空間結合（`gpd.sjoin`）して `都道府県` を付与し、表示用 `label` と検索用 `search_label` を生成する。

- **label（表示用）**: 単独駅名→`駅名` ／ 同名複数でも「複数運営会社」「同一社が別地域に衝突」は `駅名`（素）／ 単独運営会社で衝突なしは `駅名（運営会社）`
- **search_label（検索用）**: `label` に `都道府県` を付加（単一括弧）。例: 尼崎（阪神電気鉄道・兵庫県）／ 二月田（鹿児島県）／ 上道（鳥取県）
- `grp` は結合キーとして温存。`都道府県` も単独列で保持。

In [14]:
# 行政区域(N03)の都道府県ポリゴンを代表点に空間結合して 都道府県 を付与
N03_ZIP = BASE_DIR / "data" / "行政区域データ" / "N03-20260101_GML.zip"
# 都道府県名でまとまった _prefecture 版を使用。CRS は EPSG:6668 で S12 と一致（再投影不要）
pref = gpd.read_file(f"zip://{N03_ZIP}!N03-20260101_prefecture.shp", columns=["N03_001"])
pref = pref.rename(columns={"N03_001": "都道府県"})

grp_pt = gpd.GeoDataFrame(
    station_group[["grp"]].copy(),
    geometry=gpd.points_from_xy(station_group["lon"], station_group["lat"]),
    crs="EPSG:6668",
)
# 点が含まれる都道府県を判定。境界外（海上の埋立地・座標誤差）は最近傍で補完
hit = gpd.sjoin(grp_pt, pref, how="left", predicate="within").drop_duplicates("grp")[["grp", "都道府県"]]
miss = hit["都道府県"].isna()
if miss.any():
    near = (gpd.sjoin_nearest(grp_pt[grp_pt["grp"].isin(hit.loc[miss, "grp"])].to_crs(3857), pref.to_crs(3857), how="left")
            .drop_duplicates("grp").set_index("grp")["都道府県"])
    hit.loc[miss, "都道府県"] = hit.loc[miss, "grp"].map(near)

station_group = station_group.merge(hit, on="grp", how="left")
print("都道府県 付与:", int(station_group["都道府県"].notna().sum()), "/", len(station_group),
      " 未割当:", int(station_group["都道府県"].isna().sum()))
print(station_group["都道府県"].value_counts().head())

都道府県 付与: 9273 / 9273  未割当: 0
都道府県
東京都    654
北海道    558
大阪府    480
愛知県    477
兵庫県    365
Name: count, dtype: int64

In [15]:
# 表示用 label と 検索用 search_label を生成
ops_by_grp = (station_group_operator.groupby("grp")["運営会社"]
              .apply(lambda s: sorted(s.unique().tolist())).to_dict())
grps_by_name = station_group.groupby("駅名")["grp"].apply(list).to_dict()

def make_label(nm, grp):
    grps = grps_by_name[nm]
    if len(grps) == 1:                               # A: 単独駅名
        return nm
    ops = ops_by_grp.get(grp, [])
    if len(ops) != 1:                                # C: 複数運営会社 → 素
        return nm
    op = ops[0]
    for g in grps:                                   # D: 同一単独社が別地域に衝突 → 素
        if g != grp and ops_by_grp.get(g, []) == [op]:
            return nm
    return f"{nm}（{op}）"                             # B: 単独社・衝突なし → 社付き

station_group["label"] = [make_label(r["駅名"], r["grp"]) for _, r in station_group.iterrows()]

def make_search_label(label, pref):
    if pd.isna(pref):
        return label
    if label.endswith(f"（{pref}）"):                  # 運営会社名が都道府県名と同一（例: 都営=東京都）
        return label
    if label.endswith("）"):                          # 駅名（運営会社） → 駅名（運営会社・都道府県）
        return label[:-1] + "・" + pref + "）"
    return f"{label}（{pref}）"                         # 駅名 → 駅名（都道府県）

station_group["search_label"] = [make_search_label(l, p)
                                 for l, p in zip(station_group["label"], station_group["都道府県"])]

# 列順を整える（識別子を前方へ）
front = ["grp", "駅名", "label", "search_label", "都道府県", "lon", "lat"]
station_group = station_group[front + [c for c in station_group.columns if c not in front]]

# 検索ラベルの一意性チェック（将来データで同名・同県・素ラベルが衝突したら検知）
print("search_label 重複:", int(station_group["search_label"].duplicated().sum()), "（0 が正常）")
station_group.head()

search_label 重複: 0 （0 が正常）

,grp,駅名,label,search_label,都道府県,lon,lat,pax_2011,pax_2012,pax_2013,pax_2014,pax_2015,pax_2016,pax_2017,pax_2018,pax_2019,pax_2020,pax_2021,pax_2022,pax_2023,pax_2024,n_op,level_complete,rate_yoy,flag_yoy,rate_covid,flag_covid,flag_covid_lown,operators
0,JA広島病院前#0,JA広島病院前,JA広島病院前,JA広島病院前（広島県）,広島県,132.32251,34.34405,3403,3403,3403,3403,3403,3403,1674,1548,1474,1153,1085,1178,1270,1474,1,True,16.1,0,0.0,0,0,広島電鉄
1,JR三山木#0,JR三山木,JR三山木,JR三山木（京都府）,京都府,135.78427,34.79899,1484,1586,1613,1676,1800,1866,1899,2004,2138,1626,1678,1762,1924,2052,1,True,6.7,0,-4.0,0,0,西日本旅客鉄道
2,JR五位堂#0,JR五位堂,JR五位堂,JR五位堂（奈良県）,奈良県,135.71831,34.52768,1521,1493,1448,1444,1484,1526,1567,1576,1514,1246,1314,1364,1436,1424,1,True,-0.8,0,-5.9,0,0,西日本旅客鉄道
3,JR俊徳道#0,JR俊徳道,JR俊徳道,JR俊徳道（大阪府）,大阪府,135.57249,34.65830,6471,6899,7347,7512,7802,7948,8147,8394,10402,8108,9494,11170,12180,13006,1,True,6.8,0,25.0,0,0,西日本旅客鉄道
4,JR小倉#0,JR小倉,JR小倉,JR小倉（京都府）,京都府,135.78634,34.88913,3817,3828,3871,3816,3844,3724,3752,3734,3700,2828,2944,3282,3632,3992,1,True,9.9,0,7.9,0,0,西日本旅客鉄道

In [16]:
# 確認: ラベル生成の代表例（A:単独 / B:社付き / C:複数社→素 / D:同一社衝突→素）
_chk = ["二月田#0", "尼崎#0", "尼崎#1", "市役所前#0", "上道#0", "上道#1",
        "大久保#2", "大久保#3", "三田#0", "三田#1"]
station_group[station_group["grp"].isin(_chk)][["grp", "label", "search_label", "都道府県"]]

         grp        label     search_label  都道府県
389     三田#0           三田          三田（兵庫県）   兵庫県
390     三田#1      三田（東京都）          三田（東京都）   東京都
572     上道#0           上道          上道（鳥取県）   鳥取県
573     上道#1           上道          上道（岡山県）   岡山県
982    二月田#0          二月田        二月田（鹿児島県）  鹿児島県
2701   大久保#2          大久保         大久保（秋田県）   秋田県
2702   大久保#3          大久保         大久保（東京都）   東京都
3512    尼崎#0   尼崎（阪神電気鉄道）   尼崎（阪神電気鉄道・兵庫県）   兵庫県
3513    尼崎#1  尼崎（西日本旅客鉄道）  尼崎（西日本旅客鉄道・兵庫県）   兵庫県
3830  市役所前#0   市役所前（伊予鉄道）   市役所前（伊予鉄道・愛媛県）   愛媛県

In [17]:
# 確認: 代表的な駅（東京・新宿・渋谷・横浜・小諸）
_check = ["東京#0", "新宿#0", "渋谷#0", "横浜#0", "小諸#0"]
_cols = ["grp", "駅名", "n_op", "level_complete",
         "pax_2019", "pax_2024", "rate_yoy", "flag_yoy", "rate_covid", "flag_covid"]
station_group[station_group["grp"].isin(_check)][_cols]

,grp,駅名,n_op,level_complete,pax_2019,pax_2024,rate_yoy,flag_yoy,rate_covid,flag_covid
3481,小諸#0,小諸,2,False,6518,5647,119.0,1,58.0,1
4376,新宿#0,新宿,5,True,3265570,2713386,-9.1,0,-16.9,1
4933,東京#0,東京,3,False,1339555,1262604,7.3,0,-5.7,0
5524,横浜#0,横浜,6,True,2101709,1936287,-1.3,0,-7.9,1
6039,渋谷#0,渋谷,4,True,2704384,2897703,36.1,1,7.1,0

## （４）駅半径内人口（メッシュ面積按分・複数年）

`docs/population_mesh.md` §8 に基づき、駅代表点の半径 500m/1km/2km/5km/10km/20km で**面積按分**集計する。
**2020・2015年は250mメッシュ、2010・2005・2000・1995年は500mメッシュ**（2010以前の250mは全国非対応のため、全国網羅の500mを採用）。列名で年を区別（`pop_{year}_*`）。
- メッシュ幾何はコードから生成（境界shp不要）、正積図法で面積按分、内部/境界分割＋KDTree。
- `load_mesh_pop` は **解像度(9桁=500m / 10桁=250m)を自動判定**し、判定マージン `H`（投影後セル半対角の上限）も自動算出。
- 人口コードは各年 `cat01=0010` 共通。秘匿/合算フラグは2020/2015のみ（2010 500mは列がない→`hidden_ratio=NaN`）。
- 出力: 各年 `pop_{year}_500m … pop_{year}_20km`（整数）＋ `pop_{year}_500m_hidden_ratio`。

In [18]:
# 半径内人口の共通処理（複数年・複数解像度で再利用）— docs/population_mesh.md §8 準拠
import io, glob, time
import numpy as np
from pyproj import Transformer
from scipy.spatial import cKDTree
import shapely

RADII = [500, 1000, 2000, 5000, 10000, 20000]
RNAME = {500:"500m", 1000:"1km", 2000:"2km", 5000:"5km", 10000:"10km", 20000:"20km"}
QS = 32          # バッファ多角形分割（円面積99.96%再現）
AEA = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=35 +lon_0=135 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs"
tf_aea = Transformer.from_crs("EPSG:6668", AEA, always_xy=True)   # CRS.md の正積図法

def _build_geom(area):
    """メッシュコード列(str)→ 矩形ポリゴン・面積・重心・KDTree・判定マージンH。解像度はコード桁数で自動判定(10桁=250m/9桁=500m)。"""
    s = area.astype(str); L = int(s.str.len().mode()[0])
    a=s.str[0:2].astype(int); b=s.str[2:4].astype(int); c=s.str[4].astype(int); d=s.str[5].astype(int)
    e=s.str[6].astype(int); f=s.str[7].astype(int); g=s.str[8].astype(int)
    lat = a*2/3 + c*(2/3)/8 + e*(2/3)/80 + ((g-1)//2)*(1/240)
    lon = (b+100) + d/8 + f/80 + ((g-1)%2)*(1/160)
    if L == 10:                                  # 250m: 5次象限を追加
        hc = s.str[9].astype(int)
        lat = lat + ((hc-1)//2)*(1/480); lon = lon + ((hc-1)%2)*(1/320); dlat, dlon = 1/480, 1/320
    else:                                        # 9桁 = 500m
        dlat, dlon = 1/240, 1/160
    lat_s = lat.to_numpy(); lon_w = lon.to_numpy(); lat_n = lat_s+dlat; lon_e = lon_w+dlon
    xw,ys=tf_aea.transform(lon_w,lat_s); xe,ys2=tf_aea.transform(lon_e,lat_s)
    xe2,yn=tf_aea.transform(lon_e,lat_n); xw2,yn2=tf_aea.transform(lon_w,lat_n)
    rings=np.stack([np.c_[xw,ys],np.c_[xe,ys2],np.c_[xe2,yn],np.c_[xw2,yn2],np.c_[xw,ys]],axis=1)
    mcx=rings[:,:4,0].mean(1); mcy=rings[:,:4,1].mean(1)
    xx=rings[:,:,0]; yy=rings[:,:,1]
    area_a=0.5*np.abs(np.sum(xx[:,:-1]*yy[:,1:]-xx[:,1:]*yy[:,:-1],axis=1))   # shoelace=真の地表面積
    halfdiag=np.sqrt(((rings[:,:4,0]-mcx[:,None])**2+(rings[:,:4,1]-mcy[:,None])**2).max(1))
    return dict(rings=rings, mcx=mcx, mcy=mcy, area=area_a, tree=cKDTree(np.c_[mcx,mcy]),
                H=float(halfdiag.max())*1.02, res_m=(250 if L==10 else 500),
                lat_c=lat.to_numpy()+dlat/2, lon_c=lon.to_numpy()+dlon/2)   # 中心の緯度経度（§14 の市区町村判定で使う）

def load_mesh_pop(mesh_dir, pop_cat01=10, pattern="mesh*.csv"):
    """国勢調査メッシュCSV群から人口を読み、geom + pop + 秘匿フラグを構築。
    cat01=10 が人口総数、100 が15〜64歳人口（§14 の按分の重み。保存名が違うので pattern も渡す）。"""
    recs = []; has_secrecy = False
    for fp in sorted(glob.glob(str(mesh_dir / pattern))):
        lines = Path(fp).read_text(encoding="utf-8").splitlines()
        vi = next(i for i, l in enumerate(lines) if l == '"VALUE"')
        tbl = pd.read_csv(io.StringIO(chr(10).join(lines[vi+1:])))
        sub = tbl[pd.to_numeric(tbl["cat01_code"], errors="coerce") == pop_cat01]
        rec = pd.DataFrame({"area": sub["area_code"].astype(str),
                            "pop": pd.to_numeric(sub["value"], errors="coerce").fillna(0.0)})
        if "cat02_code" in tbl.columns:
            has_secrecy = True
            nm = sub.iloc[:, tbl.columns.get_loc("cat02_code") + 1].astype(str)
            rec["hidden"] = nm.isin(["合算", "秘匿"]).to_numpy()
        else:
            rec["hidden"] = False
        recs.append(rec)
    m = pd.concat(recs, ignore_index=True)
    M = _build_geom(m["area"])
    M.update(pop=m["pop"].to_numpy(), hidden=m["hidden"].to_numpy(),
             has_secrecy=has_secrecy, total=int(m["pop"].sum()), ncell=len(m))
    return M

def aggregate_radii(M, sx, sy):
    """1駅について各半径の人口と500m秘匿割合（docs §8.4）。Hはメッシュ依存。"""
    H = M["H"]; out={R:0.0 for R in RADII}; hid500=0.0
    cand=np.asarray(M["tree"].query_ball_point([sx,sy], RADII[-1]+H), dtype=int)
    if cand.size==0: return out, 0.0
    dist=np.hypot(M["mcx"][cand]-sx, M["mcy"][cand]-sy)
    for R in RADII:
        ins=dist<=R-H; band=(dist>R-H)&(dist<=R+H)
        pin=M["pop"][cand][ins]; tot=pin.sum(); hidp=pin[M["hidden"][cand][ins]].sum()
        if band.any():
            bi=cand[band]
            w=shapely.area(shapely.intersection(shapely.polygons(M["rings"][bi]),
                                                shapely.Point(sx,sy).buffer(R,quad_segs=QS)))/M["area"][bi]
            bp=M["pop"][bi]*w; tot+=bp.sum(); hidp+=bp[M["hidden"][bi]].sum()
        out[R]=tot
        if R==500 and tot>0: hid500=hidp/tot
    return out, hid500

def aggregate_radii_multi(M, pops, sx, sy):
    """複数年の人口配列(pops: {year: array})を一括集計。境界weightは年共通なので1駅×半径で1回だけ計算。"""
    H = M["H"]; out={y:{R:0.0 for R in RADII} for y in pops}
    cand=np.asarray(M["tree"].query_ball_point([sx,sy], RADII[-1]+H), dtype=int)
    if cand.size==0: return out
    dist=np.hypot(M["mcx"][cand]-sx, M["mcy"][cand]-sy)
    for R in RADII:
        ins=dist<=R-H; band=(dist>R-H)&(dist<=R+H)
        bi = cand[band] if band.any() else None
        if bi is not None:
            w=shapely.area(shapely.intersection(shapely.polygons(M["rings"][bi]),
                                                shapely.Point(sx,sy).buffer(R,quad_segs=QS)))/M["area"][bi]
        for y, parr in pops.items():
            tot = parr[cand][ins].sum()
            if bi is not None: tot += (parr[bi]*w).sum()
            out[y][R]=tot
    return out

In [19]:
# 年ごとにメッシュ人口を算出 → pop_{year}_<半径> 列を付与（2020/2015=250m, 2010/2005/2000/1995=500m）
MESH_YEARS = {
    2020: BASE_DIR / "data" / "国勢調査_人口及び世帯_2020_mesh250",
    2015: BASE_DIR / "data" / "国勢調査_人口及び世帯_2015_mesh250",
    2010: BASE_DIR / "data" / "国勢調査_人口及び世帯_2010_mesh500",
    2005: BASE_DIR / "data" / "国勢調査_人口及び世帯_2005_mesh500",
    2000: BASE_DIR / "data" / "国勢調査_人口及び世帯_2000_mesh500",
    1995: BASE_DIR / "data" / "国勢調査_人口及び世帯_1995_mesh500",
}
_sx, _sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy())
nST = len(station_group)
for year, mdir in MESH_YEARS.items():
    M = load_mesh_pop(mdir); hs = M["has_secrecy"]
    print(f"[{year}] {M['res_m']}mメッシュ {M['ncell']:,}セル 全国人口計 {M['total']:,}")
    pop_out = {R: np.zeros(nST) for R in RADII}; hid500 = np.zeros(nST)
    t0 = time.time()
    for j in range(nST):
        o, hr = aggregate_radii(M, _sx[j], _sy[j])
        for R in RADII: pop_out[R][j] = o[R]
        hid500[j] = hr
        if (j+1) % 3000 == 0: print(f"  [{year}] {j+1}/{nST} ({time.time()-t0:.0f}s)")
    arr = np.maximum.accumulate(np.column_stack([pop_out[R] for R in RADII]), axis=1)   # 単調化（float誤差対策）
    for k, R in enumerate(RADII):
        station_group[f"pop_{year}_{RNAME[R]}"] = pd.Series(np.rint(arr[:, k]), index=station_group.index).astype("Int64")
    station_group[f"pop_{year}_500m_hidden_ratio"] = np.round(hid500, 3) if hs else np.nan   # 2010は秘匿フラグなし
    print(f"  [{year}] 集計完了 {time.time()-t0:.0f}s  (秘匿フラグ: {'有' if hs else '無'})")
    del M

[2020] 250mメッシュ 1,163,757セル 全国人口計 126,146,099

  [2020] 3000/9273 (25s)

  [2020] 6000/9273 (56s)

  [2020] 9000/9273 (81s)

  [2020] 集計完了 84s  (秘匿フラグ: 有)

[2015] 250mメッシュ 1,178,130セル 全国人口計 127,094,745

  [2015] 3000/9273 (28s)

  [2015] 6000/9273 (55s)

  [2015] 9000/9273 (82s)

  [2015] 集計完了 85s  (秘匿フラグ: 有)

[2010] 500mメッシュ 477,172セル 全国人口計 128,057,352

  [2010] 3000/9273 (18s)

  [2010] 6000/9273 (36s)

  [2010] 9000/9273 (54s)

  [2010] 集計完了 55s  (秘匿フラグ: 無)

[2005] 500mメッシュ 482,181セル 全国人口計 127,767,994

  [2005] 3000/9273 (18s)

  [2005] 6000/9273 (36s)

  [2005] 9000/9273 (62s)

  [2005] 集計完了 65s  (秘匿フラグ: 無)

[2000] 500mメッシュ 308,418セル 全国人口計 126,925,843

  [2000] 3000/9273 (24s)

  [2000] 6000/9273 (39s)

  [2000] 9000/9273 (54s)

  [2000] 集計完了 55s  (秘匿フラグ: 無)

[1995] 500mメッシュ 312,515セル 全国人口計 125,570,246

  [1995] 3000/9273 (16s)

  [1995] 6000/9273 (32s)

  [1995] 9000/9273 (46s)

  [1995] 集計完了 47s  (秘匿フラグ: 無)

In [20]:
# 検証: 各年の単調性 ＋ 代表駅の年次比較（2020/2015/2010）
for year in MESH_YEARS:
    _o = [f"pop_{year}_{RNAME[R]}" for R in RADII]
    _mono = (station_group[_o].to_numpy()[:, 1:] >= station_group[_o].to_numpy()[:, :-1]).all()
    print(f"{year} 単調性 OK:", bool(_mono))
_yrs = sorted(MESH_YEARS, reverse=True)
_cols = [f"pop_{y}_{r}" for r in ["1km","5km","20km"] for y in _yrs]
station_group[station_group["grp"].isin(["東京#0","新宿#0","横浜#0","二月田#0"])][["grp","駅名"]+_cols]

2020 単調性 OK: True
2015 単調性 OK: True
2010 単調性 OK: True
2005 単調性 OK: True
2000 単調性 OK: True
1995 単調性 OK: True

,grp,駅名,pop_2020_1km,pop_2015_1km,pop_2010_1km,pop_2005_1km,pop_2000_1km,pop_1995_1km,pop_2020_5km,pop_2015_5km,pop_2010_5km,pop_2005_5km,pop_2000_5km,pop_1995_5km,pop_2020_20km,pop_2015_20km,pop_2010_20km,pop_2005_20km,pop_2000_20km,pop_1995_20km
982,二月田#0,二月田,4292,4175,4061,4081,4125,4201,25794,27038,27977,28913,29767,30442,68994,75470,81103,86390,90473,94034
4376,新宿#0,新宿,25571,24831,26067,23603,22010,21679,1380338,1307184,1244670,1189099,1147803,1119800,15461814,14786688,14298231,13587834,12992867,12635329
4933,東京#0,東京,4248,4126,5510,4412,3252,3239,1186130,1071653,957108,858654,750608,717317,13998943,13367580,12924701,12272199,11728443,11463811
5524,横浜#0,横浜,43471,41272,39004,31951,25579,22375,820477,791114,774928,743203,703679,678883,8561345,8342470,8181134,7879518,7546950,7307187

## （５）人口増減率（各半径・指定年ペア）

§（４）の年次人口から、各半径の**人口増減率**を算出する（`docs/population_mesh.md` §8.7）。
- **2020基準**（各年との比較）: 2020/2015, 2020/2010, 2020/2005, 2020/2000, 2020/1995
- **直近**（前回国勢調査との比較）: 2015/2010, 2010/2005, 2005/2000, 2000/1995
- 列名 **`pop_gr_{新しい年}_{古い年}_{半径}`**（単位%・小数1桁、分母0/欠損はNaN）。9ペア×6半径=**54列**。
- ⚠️ 250m/500m境界を跨ぐペア（2020・2015 × 2010以前）は **500m/1km半径にメッシュ段差(~3.6%/1%)** を含む（2km以上はクリーン。§6.3）。同一解像度ペア（2020/2015、および 2010/2005/2000/1995）は完全整合。

In [21]:
# 人口増減率: 指定年ペア × 各半径 → pop_gr_{新}_{旧}_{半径}（%）
POP_PAIRS = [
    (2020, 2015), (2020, 2010), (2020, 2005), (2020, 2000), (2020, 1995),  # 2020基準（各年との比較）
    (2015, 2010), (2010, 2005), (2005, 2000), (2000, 1995),                # 直近（前回国勢調査との比較）
]
for newer, older in POP_PAIRS:
    for R in RADII:
        new = station_group[f"pop_{newer}_{RNAME[R]}"].to_numpy(dtype="float64", na_value=np.nan)
        old = station_group[f"pop_{older}_{RNAME[R]}"].to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            gr = np.where(old > 0, (new / old - 1.0) * 100.0, np.nan)   # 分母0/欠損は NaN
        station_group[f"pop_gr_{newer}_{older}_{RNAME[R]}"] = np.round(gr, 1)

_grcols = [c for c in station_group.columns if c.startswith("pop_gr_")]
print(f"人口増減率 列数: {len(_grcols)}（{len(POP_PAIRS)}ペア × {len(RADII)}半径）  NaNを含む列: {sum(station_group[c].isna().any() for c in _grcols)}")
# サニティ: 東京(都心回帰で増)・二月田(地方減) の5km
station_group[station_group["grp"].isin(["東京#0","二月田#0"])][
    ["駅名","pop_gr_2020_1995_5km","pop_gr_2020_2015_5km","pop_gr_2015_2010_5km","pop_gr_2000_1995_5km"]]

人口増減率 列数: 54（9ペア × 6半径）  NaNを含む列: 34

,駅名,pop_gr_2020_1995_5km,pop_gr_2020_2015_5km,pop_gr_2015_2010_5km,pop_gr_2000_1995_5km
982,二月田,-15.3,-4.6,-3.4,-2.2
4933,東京,65.4,10.7,12.0,4.6

## （６）将来推計人口（R6・250mメッシュ, 2020–2070）

国土数値情報「将来推計人口250mメッシュ（R6国政局推計）」を、§（４）と同じ面積按分で駅半径内に集計（`docs/population_mesh.md` §10）。
- **真値フィールド `PTN_<year>`**（秘匿なし＝合算前の各セル値）を使用（合算による所在ズレを回避）。
- 都道府県別の**入れ子zip**を展開し、跨ぎメッシュは `MESH_ID` で合算（重複解消）。
- メッシュコード(10桁=250m)を §8 デコーダで矩形化 → 既存パイプライン（内部/境界分割・H自動）を再利用。
- 出力 **`pop_pred_2024_<年>_<半径>`**（R6＝2024年作成。年＝2020基準実績＋2025–2070推計。11年×6半径＝66列）。`pop_pred_2024_2020` は実績 `pop_2020` とほぼ一致（検証）。

In [22]:
# 将来推計人口 R6（250m）の読込: 入れ子zip→県別shp→MESH_ID + PTN_<year>
import zipfile, tempfile
R6_OUTER = BASE_DIR / "data" / "250mメッシュ別将来推計人口データ（R6国政局推計）" / "250m_mesh_2024_SHP.zip"
PROJ_YEARS = [2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060, 2065, 2070]  # 2020=基準実績, 2025-2070=推計
_ptn = [f"PTN_{y}" for y in PROJ_YEARS]
_parts = []
with zipfile.ZipFile(R6_OUTER) as z:
    for n in sorted(x for x in z.namelist() if x.endswith("_SHP.zip")):   # 47都道府県
        with tempfile.TemporaryDirectory() as td:
            z.extract(n, td)
            with zipfile.ZipFile(Path(td) / n) as z2:
                z2.extractall(td)
            shp = next(Path(td).rglob("*.shp"))
            _parts.append(pd.DataFrame(gpd.read_file(shp, columns=["MESH_ID"] + _ptn, ignore_geometry=True)))
r6 = pd.concat(_parts, ignore_index=True)
# 都道府県跨ぎの分割メッシュ(同一MESH_IDが複数県に分割計上)を合算して統合
r6 = r6.groupby("MESH_ID", as_index=False)[_ptn].sum()
print(f"R6 250m: {len(r6):,}セル  PTN_2020={int(r6['PTN_2020'].sum()):,}（実績2020=126,146,099と僅差）  PTN_2070={int(r6['PTN_2070'].sum()):,}")

R6 250m: 1,162,630セル  PTN_2020=126,146,098（実績2020=126,146,099と僅差）  PTN_2070=86,996,003

In [23]:
# geometry を1回構築し、全推計年を一括集計（境界weightは年共通→高速）→ pop_pred_2024_<年>_<半径>
Mr6 = _build_geom(r6["MESH_ID"])
_pops = {y: r6[f"PTN_{y}"].fillna(0).to_numpy(dtype="float64") for y in PROJ_YEARS}
_sx, _sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy())
nST = len(station_group)
_acc = {y: {R: np.zeros(nST) for R in RADII} for y in PROJ_YEARS}
_t0 = time.time()
for j in range(nST):
    o = aggregate_radii_multi(Mr6, _pops, _sx[j], _sy[j])
    for y in PROJ_YEARS:
        for R in RADII: _acc[y][R][j] = o[y][R]
    if (j+1) % 3000 == 0: print(f"  {j+1}/{nST} ({time.time()-_t0:.0f}s)")
for y in PROJ_YEARS:
    arr = np.maximum.accumulate(np.column_stack([_acc[y][R] for R in RADII]), axis=1)   # 単調化
    for k, R in enumerate(RADII):
        station_group[f"pop_pred_2024_{y}_{RNAME[R]}"] = pd.Series(np.rint(arr[:, k]), index=station_group.index).astype("Int64")
print(f"R6集計完了 {time.time()-_t0:.0f}s  追加列: {len([c for c in station_group.columns if c.startswith('pop_pred_2024_')])}")

  3000/9273 (32s)

  6000/9273 (63s)

  9000/9273 (93s)

R6集計完了 95s  追加列: 66

In [24]:
# 検証: 基準年(R6 2020)≒実績2020 / 将来の推移、各年の単調性
_bad = [y for y in PROJ_YEARS if not (station_group[[f"pop_pred_2024_{y}_{RNAME[R]}" for R in RADII]].to_numpy()[:,1:] >= station_group[[f"pop_pred_2024_{y}_{RNAME[R]}" for R in RADII]].to_numpy()[:,:-1]).all()]
print("単調性 違反年:", _bad if _bad else "なし(全年OK)")
station_group[station_group["grp"].isin(["東京#0","新宿#0","二月田#0"])][
    ["駅名","pop_2020_5km","pop_pred_2024_2020_5km","pop_pred_2024_2050_5km","pop_pred_2024_2070_5km"]]

単調性 違反年: なし(全年OK)

,駅名,pop_2020_5km,pop_pred_2024_2020_5km,pop_pred_2024_2050_5km,pop_pred_2024_2070_5km
982,二月田,25794,25771,16635,11722
4376,新宿,1380338,1379926,1480708,1404340
4933,東京,1186130,1182055,1379704,1342849

## （７）将来推計人口（H30・500mメッシュ, 2015–2050）

国土数値情報「将来推計人口500mメッシュ（H30国政局推計）」を §（６）と同じ面積按分で集計（`docs/population_mesh.md` §10）。
- 2015国勢調査ベース・2050まで。**真値 `PTN_<year>`** 使用。CRSは4612(JGD2000)だがメッシュコードから矩形生成（EPSG:6668扱い・差<1m）。
- 都道府県別zip（shp直下・入れ子なし）。メッシュ重複なし（groupbyは安全網）。
- 出力 **`pop_pred_2018_<年>_<半径>`**（H30＝2018年作成。2015基準＋2020–2050。8年×6半径＝48列）。
- 注: `pop_pred_2018_2020` はH30の2020「予測」（2018時点）であり、実績 `pop_2020` やR6 `pop_pred_2024_2020` とは別物（予測誤差の確認に有用）。

In [25]:
# 将来推計人口 H30（500m）の読込: 都道府県別zip(shp直下)→ MESH_ID + PTN_<year>
import zipfile
H30_DIR = BASE_DIR / "data" / "500mメッシュ別将来推計人口データ（H30国政局推計）"
PROJ_YEARS_H30 = [2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050]  # 2015=基準実績, 2020-2050=推計
_ptn_h30 = [f"PTN_{y}" for y in PROJ_YEARS_H30]
_parts = []
for zp in sorted(H30_DIR.glob("500m_mesh_suikei_2018_shape_*.zip")):   # 47都道府県
    with zipfile.ZipFile(zp) as z:
        _shp = next(n for n in z.namelist() if n.endswith(".shp"))
    _parts.append(pd.DataFrame(gpd.read_file(f"zip://{zp}!{_shp}", columns=["MESH_ID"] + _ptn_h30, ignore_geometry=True)))
h30 = pd.concat(_parts, ignore_index=True)
h30["MESH_ID"] = h30["MESH_ID"].astype(str)
h30 = h30.groupby("MESH_ID", as_index=False)[_ptn_h30].sum()   # 念のため重複統合
print(f"H30 500m: {len(h30):,}セル  PTN_2015={int(h30['PTN_2015'].sum()):,}（実績2015=127,094,745と僅差）  PTN_2050={int(h30['PTN_2050'].sum()):,}")

H30 500m: 471,024セル  PTN_2015=127,094,385（実績2015=127,094,745と僅差）  PTN_2050=101,922,983

In [26]:
# geometry を1回構築し全推計年を一括集計 → pop_pred_2018_<年>_<半径>
Mh30 = _build_geom(h30["MESH_ID"])
_pops_h30 = {y: h30[f"PTN_{y}"].fillna(0).to_numpy(dtype="float64") for y in PROJ_YEARS_H30}
_sxh, _syh = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy())
nST = len(station_group)
_acch = {y: {R: np.zeros(nST) for R in RADII} for y in PROJ_YEARS_H30}
_t0 = time.time()
for j in range(nST):
    o = aggregate_radii_multi(Mh30, _pops_h30, _sxh[j], _syh[j])
    for y in PROJ_YEARS_H30:
        for R in RADII: _acch[y][R][j] = o[y][R]
    if (j+1) % 3000 == 0: print(f"  {j+1}/{nST} ({time.time()-_t0:.0f}s)")
for y in PROJ_YEARS_H30:
    arr = np.maximum.accumulate(np.column_stack([_acch[y][R] for R in RADII]), axis=1)   # 単調化
    for k, R in enumerate(RADII):
        station_group[f"pop_pred_2018_{y}_{RNAME[R]}"] = pd.Series(np.rint(arr[:, k]), index=station_group.index).astype("Int64")
print(f"H30集計完了 {time.time()-_t0:.0f}s  追加列: {len([c for c in station_group.columns if c.startswith('pop_pred_2018_')])}")

  3000/9273 (19s)

  6000/9273 (39s)

  9000/9273 (61s)

H30集計完了 64s  追加列: 48

In [27]:
# 検証: 基準年(H30 2015)≒実績2015 / H30の2020予測 vs 実績・R6 / 単調性
_bad = [y for y in PROJ_YEARS_H30 if not (station_group[[f"pop_pred_2018_{y}_{RNAME[R]}" for R in RADII]].to_numpy()[:,1:] >= station_group[[f"pop_pred_2018_{y}_{RNAME[R]}" for R in RADII]].to_numpy()[:,:-1]).all()]
print("H30 単調性 違反年:", _bad if _bad else "なし(全年OK)")
station_group[station_group["grp"].isin(["東京#0","二月田#0"])][
    ["駅名","pop_2015_5km","pop_pred_2018_2015_5km","pop_2020_5km","pop_pred_2018_2020_5km","pop_pred_2024_2020_5km","pop_pred_2018_2050_5km","pop_pred_2024_2050_5km"]]

H30 単調性 違反年: なし(全年OK)

,駅名,pop_2015_5km,pop_pred_2018_2015_5km,pop_2020_5km,pop_pred_2018_2020_5km,pop_pred_2024_2020_5km,pop_pred_2018_2050_5km,pop_pred_2024_2050_5km
982,二月田,27038,27095,25794,25645,25771,16213,16635
4933,東京,1071653,1084871,1186130,1157019,1182055,1306333,1379704

## （８）将来人口増減率（実績2020 → R6推計各年）

「最新の確定実績（2020国勢調査）」を起点に、R6将来推計（2024）の各年への**人口増減率**を算出（`docs/population_mesh.md` §8.8）。
- 分母＝**実績 `pop_2020_{半径}`**（公式・最も正確な2020実績）。分子＝**`pop_pred_2024_{年}_{半径}`**（R6推計, 2025–2070）。
- 列名 **`pop_gr_pred_2024_{年}_{半径}`**（%・小数1桁、分母0/欠損はNaN）。10年×6半径＝**60列**。
- 起点は2020実績で固定。R6の2020基準(`pop_pred_2024_2020`)との出典差は~0.3%（許容）。両者250mでメッシュ段差なし。
- `pred_2024` で実績増減率 `pop_gr_{年}_{年}` と区別。

In [28]:
# 将来人口増減率: 実績2020(国勢調査) を起点に R6推計各年 → pop_gr_pred_2024_{年}_{半径}（%）
PRED_GR_YEARS = [2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060, 2065, 2070]  # R6推計年（2020基準実績は分母なので除く）
_fgcols = {}
for year in PRED_GR_YEARS:
    for R in RADII:
        new = station_group[f"pop_pred_2024_{year}_{RNAME[R]}"].to_numpy(dtype="float64", na_value=np.nan)
        old = station_group[f"pop_2020_{RNAME[R]}"].to_numpy(dtype="float64", na_value=np.nan)   # 実績2020が分母
        with np.errstate(divide="ignore", invalid="ignore"):
            _fgcols[f"pop_gr_pred_2024_{year}_{RNAME[R]}"] = np.round(np.where(old > 0, (new / old - 1.0) * 100.0, np.nan), 1)
# 断片化回避のため一括結合
station_group = pd.concat([station_group, pd.DataFrame(_fgcols, index=station_group.index)], axis=1)
_fg = [c for c in station_group.columns if c.startswith("pop_gr_pred_2024_")]
print(f"将来人口増減率 列数: {len(_fg)}（{len(PRED_GR_YEARS)}年 × {len(RADII)}半径）  NaNを含む列: {sum(station_group[c].isna().any() for c in _fg)}")
# サニティ: 東京(増)・二月田(減) の5km
station_group[station_group["grp"].isin(["東京#0","二月田#0"])][
    ["駅名","pop_gr_pred_2024_2030_5km","pop_gr_pred_2024_2050_5km","pop_gr_pred_2024_2070_5km"]]

将来人口増減率 列数: 60（10年 × 6半径）  NaNを含む列: 30

,駅名,pop_gr_pred_2024_2030_5km,pop_gr_pred_2024_2050_5km,pop_gr_pred_2024_2070_5km
982,二月田,-12.3,-35.5,-54.6
4933,東京,8.2,16.3,13.2

## （９）予測誤差（H30推計2020 ÷ 国勢調査2020実績）

In [29]:
# 予測誤差: H30推計の2020予測 ÷ 国勢調査2020実績 → pop_err_2020_pred_2018_{半径}（%, 表記B）
#   式: (予測 / 実績 − 1) × 100  ＝ (pop_pred_2018_2020 / pop_2020 − 1) × 100
#   符号: ＋過大予測 / −過小予測（実績が分母）。信頼度は2km以上が高く、500mは参考。
_errcols = {}
for R in RADII:
    pred = station_group[f"pop_pred_2018_2020_{RNAME[R]}"].to_numpy(dtype="float64", na_value=np.nan)  # H30の2020予測
    act  = station_group[f"pop_2020_{RNAME[R]}"].to_numpy(dtype="float64", na_value=np.nan)            # 国勢調査2020実績(分母)
    with np.errstate(divide="ignore", invalid="ignore"):
        _errcols[f"pop_err_2020_pred_2018_{RNAME[R]}"] = np.round(np.where(act > 0, (pred / act - 1.0) * 100.0, np.nan), 1)
station_group = pd.concat([station_group, pd.DataFrame(_errcols, index=station_group.index)], axis=1)  # 断片化回避のため一括結合
_er = [c for c in station_group.columns if c.startswith("pop_err_2020_pred_2018_")]
e5 = station_group["pop_err_2020_pred_2018_5km"].to_numpy("float64")
e5 = e5[~np.isnan(e5)]
print(f"予測誤差 列数: {len(_er)}（{len(RADII)}半径）  "
      f"全国5km → 中央値 {np.median(e5):+.1f}% / MAPE {np.mean(np.abs(e5)):.1f}% / 過小予測 {(e5 < 0).mean() * 100:.0f}%")
# サニティ: 代表駅 × 全半径（＋過大 / −過小）
station_group[station_group["grp"].isin(["東京#0", "新宿#0", "二月田#0"])][
    ["駅名"] + [f"pop_err_2020_pred_2018_{RNAME[R]}" for R in RADII]]

予測誤差 列数: 6（6半径）  全国5km → 中央値 -0.6% / MAPE 2.4% / 過小予測 60%

,駅名,pop_err_2020_pred_2018_500m,pop_err_2020_pred_2018_1km,pop_err_2020_pred_2018_2km,pop_err_2020_pred_2018_5km,pop_err_2020_pred_2018_10km,pop_err_2020_pred_2018_20km
982,二月田,-21.9,-12.4,-5.7,-0.6,1.2,1.2
4376,新宿,158.9,9.5,-0.4,-1.8,-2.8,-2.2
4933,東京,182.5,47.1,-7.3,-2.5,-2.5,-2.4

## （10）信頼性フラグ（率の分母＝基準人口の大小）

In [30]:
# 信頼性フラグ: 率の分母＝基準人口 pop_{year}_{radius} が小さいと増減率・予測誤差が不安定
#   （例 和歌山大学前 base=1人→+388,100%／福島避難区域 2015≈0人）。データは正しい実態だが「参考値」と区別する。
#   pop_lowbase_{year}_{radius} = 1（base < 50人, 参考扱い） / 0（信頼）。各率は「分母の年×半径」のフラグを参照:
#     pop_gr_{新}_{旧}_{R}        → pop_lowbase_{旧}_{R}
#     pop_gr_pred_2024_{年}_{R}   → pop_lowbase_2020_{R}
#     pop_err_2020_pred_2018_{R}  → pop_lowbase_2020_{R}
LOWBASE_T = 50
_flag = {}
for year in [1995, 2000, 2005, 2010, 2015, 2020]:
    for R in RADII:
        base = station_group[f"pop_{year}_{RNAME[R]}"].to_numpy(dtype="float64")  # 実績人口はNaNなし
        _flag[f"pop_lowbase_{year}_{RNAME[R]}"] = (base < LOWBASE_T).astype("int8")
station_group = pd.concat([station_group, pd.DataFrame(_flag, index=station_group.index)], axis=1)  # 断片化回避
_lb = [c for c in station_group.columns if c.startswith("pop_lowbase_")]
print(f"信頼性フラグ 列数: {len(_lb)}（6年 × {len(RADII)}半径, 閾値 base<{LOWBASE_T}人）")
print("基準年別 low-base 駅数（半径別。≥5kmでほぼ消え20kmは0＝大半径は安定）:")
for year in [2020, 2015, 1995]:
    print(f"  {year}: " + "  ".join(f"{RNAME[R]}={int(station_group[f'pop_lowbase_{year}_{RNAME[R]}'].sum())}" for R in RADII))
# サニティ: 新興/災害駅は1、通常駅(浦和)は0
station_group[station_group["駅名"].isin(["和歌山大学前", "双葉", "浦和"])][
    ["駅名", "pop_2000_1km", "pop_lowbase_2000_1km", "pop_2015_10km", "pop_lowbase_2015_10km", "pop_lowbase_2020_5km"]]

信頼性フラグ 列数: 36（6年 × 6半径, 閾値 base<50人）
基準年別 low-base 駅数（半径別。≥5kmでほぼ消え20kmは0＝大半径は安定）:
  2020: 500m=468  1km=198  2km=91  5km=12  10km=3  20km=0
  2015: 500m=417  1km=179  2km=79  5km=15  10km=6  20km=0
  1995: 500m=341  1km=120  2km=52  5km=5  10km=0  20km=0

,駅名,pop_2000_1km,pop_lowbase_2000_1km,pop_2015_10km,pop_lowbase_2015_10km,pop_lowbase_2020_5km
2214,双葉,3507,0,1,1,0
2382,和歌山大学前,1,1,337174,0,0
5930,浦和,36636,0,2470225,0,0

## （11）地価公示（駅×半径の地価・各年推移）

`docs/land_price.md` §9 準拠。2026ファイルの内包系列（1983–2026）から、駅グループの **地価特徴量** を生成する。中央値・最寄点・各年水準パネル（グラフ用・開始2007）・増減率（no-match・年ペア）。採用 n≥1／n=0→Null、低信頼フラグ `lp_n<5`。

In [31]:
# （11）地価公示（L01・2026内包系列）→ 駅×半径の地価特徴量。docs/land_price.md §9 準拠
import zipfile, time
from pyproj import Transformer
from scipy.spatial import cKDTree

LP_ZIP = BASE_DIR / "data" / "地価公示" / "L01-26_GML.zip"
def _lpcol(y): return f"L01_{62 + (y - 1983):03d}"          # 1983=L01_062 .. 2026=L01_105
LP_PANEL_YEARS = list(range(2007, 2027))                    # 各年水準（グラフ・開始2007）
LP_GR_BASES    = [2025, 2023, 2021, 2016, 2011]             # 1y/3y/5y/10y/15y（2026基準）
LP_RADII       = [500, 1000, 2000, 5000, 10000]             # 水準・パネル
LP_GR_RADII    = [1000, 2000, 5000, 10000]                  # 増減率（500mは1点比でノイズ大→除外）
LP_RN          = {500: "500m", 1000: "1km", 2000: "2km", 5000: "5km", 10000: "10km"}
USE_MAP        = {"000": "住宅地", "003": "宅地見込地", "005": "商業地", "009": "工業地", "013": "調整区域内宅地等"}

with zipfile.ZipFile(LP_ZIP) as z:
    _shp = next(n for n in z.namelist() if n.lower().endswith(".shp"))
_need = ["L01_002", "L01_008"] + [_lpcol(y) for y in LP_PANEL_YEARS]
lp = gpd.read_file(f"/vsizip/{LP_ZIP}/{_shp}", columns=_need)   # 2026・EPSG:6668（数値/ASCII列のみ＝文字コード非依存）
if lp.crs is None: lp = lp.set_crs("EPSG:6668")

PYmat = np.column_stack([pd.to_numeric(lp[_lpcol(y)], errors="coerce").fillna(0).to_numpy(float) for y in LP_PANEL_YEARS])
Y2I = {y: i for i, y in enumerate(LP_PANEL_YEARS)}
p2026 = pd.to_numeric(lp["L01_008"], errors="coerce").to_numpy(float)            # 当年価格(=L01_105)
use_lab = pd.Series(lp["L01_002"].astype(str)).map(USE_MAP).fillna(lp["L01_002"].astype(str)).to_numpy()

lpx, lpy = tf_aea.transform(lp.geometry.x.to_numpy(), lp.geometry.y.to_numpy())  # 点・駅とも 6668→Albers
lp_tree = cKDTree(np.c_[lpx, lpy])
sx, sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy())
nST = len(station_group)
print(f"地価2026: {len(lp):,}点  CRS={lp.crs}  パネル年={LP_PANEL_YEARS[0]}–{LP_PANEL_YEARS[-1]}")

# 最寄点（20km以内・k=1。20km内に無ければNaN）
dN, iN = lp_tree.query(np.c_[sx, sy], k=1, distance_upper_bound=20000)
okN = np.isfinite(dN); safeN = np.where(okN, iN, 0)
lp_near_price = np.where(okN, p2026[safeN], np.nan)
lp_near_dist  = np.where(okN, dN, np.nan)
lp_near_use   = np.where(okN, use_lab[safeN], None)

# 半径内 各年 median/点数（最大10km球を1回→半径マスク）。0＝その年は標準地でない→除外
panel_med = {y: {R: np.full(nST, np.nan) for R in LP_RADII} for y in LP_PANEL_YEARS}
panel_n   = {y: {R: np.zeros(nST, int)  for R in LP_RADII} for y in LP_PANEL_YEARS}
_ball = lp_tree.query_ball_point(np.c_[sx, sy], max(LP_RADII)); _t0 = time.time()
for j in range(nST):
    cand = np.asarray(_ball[j], dtype=int)
    if cand.size == 0: continue
    d = np.hypot(lpx[cand] - sx[j], lpy[cand] - sy[j]); sub_all = PYmat[cand]
    for R in LP_RADII:
        m = d <= R
        if not m.any(): continue
        sub = sub_all[m]
        for y in LP_PANEL_YEARS:
            col = sub[:, Y2I[y]]; pos = col[col > 0]
            if pos.size:
                panel_n[y][R][j] = pos.size; panel_med[y][R][j] = np.median(pos)
    if (j + 1) % 3000 == 0: print(f"  {j+1}/{nST} ({time.time()-_t0:.0f}s)")
print(f"  半径集計完了 {time.time()-_t0:.0f}s")

# スカラー特徴を station_group に付与（lp_ 接頭辞）。採用 n≥1／n=0→NaN、フラグ lp_n<5
_lp = {"lp_near_price": pd.Series(np.round(lp_near_price)).astype("Int64"),
       "lp_near_dist_m": pd.Series(np.round(lp_near_dist)).astype("Int64"),
       "lp_near_use": lp_near_use}
for R in LP_RADII:
    rn = LP_RN[R]
    for y in LP_PANEL_YEARS:                                    # 各年水準を lp_med_{年}_{半径} 列に（pop と同形式で時系列化）
        _lp[f"lp_med_{y}_{rn}"] = pd.Series(np.round(panel_med[y][R])).astype("Int64")
    _lp[f"lp_n_{rn}"]    = panel_n[2026][R].astype("int64")     # 現在(2026)の点数
    _lp[f"lp_lown_{rn}"] = (panel_n[2026][R] < 5).astype("int8")  # 現在(2026)の低分母フラグ
for base in LP_GR_BASES:
    for R in LP_GR_RADII:
        rn = LP_RN[R]; new = panel_med[2026][R]; old = panel_med[base][R]
        with np.errstate(divide="ignore", invalid="ignore"):
            _lp[f"lp_gr_2026_{base}_{rn}"] = np.round(np.where((old > 0) & (new > 0), (new / old - 1.0) * 100.0, np.nan), 1)
        _lp[f"lp_gr_lown_2026_{base}_{rn}"] = (np.minimum(panel_n[2026][R], panel_n[base][R]) < 5).astype("int8")
station_group = pd.concat([station_group, pd.DataFrame(_lp, index=station_group.index)], axis=1)  # 断片化回避

# 各年水準パネル（グラフ用・ロング形式・n≥1のみ）→ 別CSV（保存セル）
_grp = station_group["grp"].to_numpy(); _parts = []
for y in LP_PANEL_YEARS:
    for R in LP_RADII:
        n = panel_n[y][R]; keep = n > 0
        if keep.any():
            _parts.append(pd.DataFrame({"grp": _grp[keep], "year": y, "radius": LP_RN[R],
                                        "lp_med": np.round(panel_med[y][R][keep]).astype("int64"),
                                        "lp_n": n[keep].astype("int64")}))
lp_panel = pd.concat(_parts, ignore_index=True)

_lpc = [c for c in station_group.columns if c.startswith("lp_")]
print(f"地価スカラー列: {len(_lpc)}（最寄3＋水準/点数/フラグ15＋増減率/フラグ40）  各年水準パネル行(n≥1): {len(lp_panel):,}")
# サニティ: 都心(高)・地方(低)
station_group[station_group["駅名"].isin(["東京", "大阪", "二月田"])][
    ["駅名", "lp_near_price", "lp_near_use", "lp_med_2026_2km", "lp_n_2km", "lp_med_2026_5km", "lp_gr_2026_2016_5km", "lp_gr_2026_2011_5km"]]

地価2026: 25,565点  CRS=EPSG:6668  パネル年=2007–2026

  3000/9273 (5s)

  6000/9273 (8s)

  9000/9273 (11s)

  半径集計完了 11s
地価スカラー列: 153（最寄3＋水準/点数/フラグ15＋増減率/フラグ40）  各年水準パネル行(n≥1): 674,105

,駅名,lp_near_price,lp_near_use,lp_med_2026_2km,lp_n_2km,lp_med_2026_5km,lp_gr_2026_2016_5km,lp_gr_2026_2011_5km
982,二月田,16500,住宅地,16500,1,21350,-20.9,-36.8
2956,大阪,24700000,商業地,1770000,51,884500,102.9,119.5
4933,東京,37600000,商業地,5540000,84,2820000,115.3,104.3

## （12）バス停数（P11 一般 ＋ P36 高速 → 物理停留所・2010増減率）

`docs/bus_point.md` 準拠。現行 P11(2022)＋P36(2023) を合算し **≤25m連結で重複排除（物理停留所）**、駅半径内の停留所数を算出（総数・一般/高速内訳）。過去 P11(2010・デマンド除外) との増減率も算出（極小分母は `bus_gr_lown` で識別）。

In [32]:
# （12）バス停数（国土数値情報 P11＋P36）→ 駅×半径の停留所数・2010増減率。docs/bus_point.md 準拠
import zipfile, tempfile, glob, time
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components

BUS_DIR = BASE_DIR / "data" / "バス停留所データ"
HW_ZIP  = BASE_DIR / "data" / "高速バス停留所データ" / "P36-23_SHP.zip"
BUS_RADII = [500, 1000, 2000, 5000, 10000, 20000]
BRN = {500:"500m", 1000:"1km", 2000:"2km", 5000:"5km", 10000:"10km", 20000:"20km"}
tf_aea_4612 = Transformer.from_crs("EPSG:4612", AEA, always_xy=True)   # 2010(JGD2000)用

def _bus_dedup(x, y, src=None):
    """≤25m連結成分で物理停留所に集約（重心）。src(0=P11/1=P36)があれば各クラスタの含有フラグも返す。"""
    pr = cKDTree(np.c_[x, y]).query_pairs(25, output_type="ndarray")
    m = coo_matrix((np.ones(len(pr)), (pr[:, 0], pr[:, 1])), shape=(len(x), len(x)))
    _, lab = connected_components(m, directed=False)
    df = pd.DataFrame({"lab": lab, "x": x, "y": y})
    if src is None:
        g = df.groupby("lab").agg(x=("x", "mean"), y=("y", "mean"))
        return g["x"].to_numpy(), g["y"].to_numpy()
    df["s0"] = (src == 0); df["s1"] = (src == 1)
    g = df.groupby("lab").agg(x=("x", "mean"), y=("y", "mean"), h11=("s0", "any"), h36=("s1", "any"))
    return g["x"].to_numpy(), g["y"].to_numpy(), g["h11"].to_numpy(), g["h36"].to_numpy()

# --- 現行: P11(2022 一般・入れ子zip→geojson) ＋ P36(2023 高速・/vsizip/geojson) ---
_t0 = time.time(); _X = []; _Y = []; _S = []
with zipfile.ZipFile(BUS_DIR / "2022" / "P11-22_SHP.zip") as z:
    for inner in sorted(n for n in z.namelist() if n.endswith("_GML.zip")):
        with tempfile.TemporaryDirectory() as td:
            z.extract(inner, td)
            with zipfile.ZipFile(Path(td) / inner) as z2: z2.extractall(td)
            g = gpd.read_file(next(Path(td).rglob("*.geojson")), columns=["P11_001"])
            _X.append(g.geometry.x.to_numpy()); _Y.append(g.geometry.y.to_numpy()); _S.append(np.zeros(len(g), int))
with zipfile.ZipFile(HW_ZIP) as z:
    for n in sorted(x for x in z.namelist() if x.endswith(".geojson")):
        g = gpd.read_file(f"/vsizip/{HW_ZIP}/{n}", columns=["P36_001"])
        if len(g): _X.append(g.geometry.x.to_numpy()); _Y.append(g.geometry.y.to_numpy()); _S.append(np.ones(len(g), int))
_src = np.concatenate(_S)
cxd, cyd, ch11, ch36 = _bus_dedup(*tf_aea.transform(np.concatenate(_X), np.concatenate(_Y)), src=_src)
print(f"現行バス: 生{len(_src):,}（P11 {int((_src==0).sum()):,}+P36 {int((_src==1).sum()):,}）→ 物理停留所 {len(cxd):,}（一般{int(ch11.sum()):,}/高速{int(ch36.sum()):,}） {time.time()-_t0:.0f}s")

# --- 過去: P11(2010 県別zip→shp/cp932/CRS=4612)・デマンド(区分コード4)除外 ---
_t0 = time.time(); _X = []; _Y = []
for zp in sorted(glob.glob(str(BUS_DIR / "2010" / "P11-10_*_GML.zip"))):
    with tempfile.TemporaryDirectory() as td:
        with zipfile.ZipFile(zp) as z: z.extractall(td)
        g = gpd.read_file(next(Path(td).rglob("*.shp")), columns=["P11_002"], encoding="cp932")  # P11_002=区分コード
        keep = g["P11_002"].astype(str).map(lambda s: len(set(c.strip() for c in s.split(",")) - {"4","0","None",""}) > 0).to_numpy()
        _X.append(g.geometry.x.to_numpy()[keep]); _Y.append(g.geometry.y.to_numpy()[keep])
c10x, c10y = _bus_dedup(*tf_aea_4612.transform(np.concatenate(_X), np.concatenate(_Y)))
print(f"2010バス: デマンド除外後 → 物理停留所 {len(c10x):,}  {time.time()-_t0:.0f}s")

# --- 駅半径内カウント（現行 総数/一般/高速 ＋ 2010） ---
_sx, _sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy()); nST = len(station_group)
_tc = cKDTree(np.c_[cxd, cyd]); _t10 = cKDTree(np.c_[c10x, c10y])
bn = {R: np.zeros(nST, int) for R in BUS_RADII}; bl = {R: np.zeros(nST, int) for R in BUS_RADII}
bh = {R: np.zeros(nST, int) for R in BUS_RADII}; b10 = {R: np.zeros(nST, int) for R in BUS_RADII}
_bc = _tc.query_ball_point(np.c_[_sx, _sy], 20000); _b10 = _t10.query_ball_point(np.c_[_sx, _sy], 20000); _t0 = time.time()
for j in range(nST):
    ic = np.asarray(_bc[j], int)
    if ic.size:
        d = np.hypot(cxd[ic]-_sx[j], cyd[ic]-_sy[j]); h11 = ch11[ic]; h36 = ch36[ic]
        for R in BUS_RADII:
            mm = d <= R; bn[R][j] = mm.sum(); bl[R][j] = h11[mm].sum(); bh[R][j] = h36[mm].sum()
    i0 = np.asarray(_b10[j], int)
    if i0.size:
        d0 = np.hypot(c10x[i0]-_sx[j], c10y[i0]-_sy[j])
        for R in BUS_RADII: b10[R][j] = (d0 <= R).sum()
    if (j+1) % 3000 == 0: print(f"  {j+1}/{nST} ({time.time()-_t0:.0f}s)")

# --- station_group へ付与（bus_ 接頭辞・系統別にまとめる） ---
_bus = {}
for R in BUS_RADII: _bus[f"bus_n_{BRN[R]}"] = bn[R].astype("int64")
for R in BUS_RADII: _bus[f"bus_n_local_{BRN[R]}"] = bl[R].astype("int64")
for R in BUS_RADII: _bus[f"bus_n_hw_{BRN[R]}"] = bh[R].astype("int64")
for R in BUS_RADII: _bus[f"bus_n2010_{BRN[R]}"] = b10[R].astype("int64")
for R in BUS_RADII:
    with np.errstate(divide="ignore", invalid="ignore"):
        _bus[f"bus_gr_{BRN[R]}"] = np.round(np.where(b10[R] > 0, (bn[R] / b10[R] - 1.0) * 100.0, np.nan), 1)
for R in BUS_RADII: _bus[f"bus_gr_lown_{BRN[R]}"] = (b10[R] < 5).astype("int8")
station_group = pd.concat([station_group, pd.DataFrame(_bus, index=station_group.index)], axis=1)

_busc = [c for c in station_group.columns if c.startswith("bus_")]
print(f"バス列数: {len(_busc)}（総数6＋一般6＋高速6＋2010:6＋増減率6＋フラグ6）  全国増減 {(len(cxd)/len(c10x)-1)*100:+.1f}%")
# サニティ: 都心(多・増) vs 地方(少・減)
station_group[station_group["駅名"].isin(["東京", "大阪", "二月田"])][
    ["駅名", "bus_n_500m", "bus_n_2km", "bus_n_hw_2km", "bus_n2010_2km", "bus_gr_2km", "bus_gr_lown_2km"]]

現行バス: 生287,739（P11 278,515+P36 9,224）→ 物理停留所 241,708（一般240,226/高速4,694） 24s

2010バス: デマンド除外後 → 物理停留所 244,431  3s

  3000/9273 (1s)

  6000/9273 (2s)

  9000/9273 (3s)

バス列数: 36（総数6＋一般6＋高速6＋2010:6＋増減率6＋フラグ6）  全国増減 -1.1%

,駅名,bus_n_500m,bus_n_2km,bus_n_hw_2km,bus_n2010_2km,bus_gr_2km,bus_gr_lown_2km
982,二月田,7,31,0,37,-16.2,0
2956,大阪,17,99,12,123,-19.5,0
4933,東京,17,159,25,149,6.7,0

## （13）事業所数・従業者数（経済センサス活動調査・500mメッシュ・民営A-R・面積按分・3年）

In [33]:
# （13）事業所数・従業者数（経済センサス活動調査 500mメッシュ・民営A-R・3年）→ 駅×半径の面積按分。docs/establishment_employee.md 準拠
import glob, io, zipfile, time

ECO_DIR = BASE_DIR / "data" / "経済センサス_活動調査_事業所数及び従業者数"
ECO_YEARS = [2021, 2016, 2012]

def _load_eco(year):
    """経済センサス 500mメッシュの (メッシュコード, 事業所数, 従業者数) を全区画読込（民営A-R）。2021=生zip(T001162002/023)・2016/2012=整形済CSV(estab/emp)。"""
    codes = []; est = []; emp = []
    if year == 2021:
        for zp in sorted(glob.glob(str(ECO_DIR / "2021" / "tblT001162H*.zip"))):
            with zipfile.ZipFile(zp) as z: txt = z.read(z.namelist()[0]).decode("shift_jis")
            df = pd.read_csv(io.StringIO(txt), dtype=str)
            df = df[df["KEY_CODE"].str.match(r"^\d+$", na=False)]                  # ラベル行除外＝メッシュ行のみ
            codes.append(df["KEY_CODE"].to_numpy())
            est.append(pd.to_numeric(df["T001162002"], errors="coerce").fillna(0).to_numpy())   # 事業所数 A〜R民営
            emp.append(pd.to_numeric(df["T001162023"], errors="coerce").fillna(0).to_numpy())   # 従業者数 A〜R民営
    else:
        for fp in sorted(glob.glob(str(ECO_DIR / str(year) / f"eco{year}_*.csv"))):
            df = pd.read_csv(fp, dtype={"KEY_CODE": str})
            codes.append(df["KEY_CODE"].to_numpy())
            est.append(pd.to_numeric(df["estab"], errors="coerce").fillna(0).to_numpy())
            emp.append(pd.to_numeric(df["emp"], errors="coerce").fillna(0).to_numpy())
    return np.concatenate(codes), np.concatenate(est).astype(float), np.concatenate(emp).astype(float)

# --- 年ごとに 500mメッシュ → 駅半径へ面積按分（人口の _build_geom / aggregate_radii_multi を流用） ---
_sx, _sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy()); nST = len(station_group)
EST = {y: {R: np.zeros(nST) for R in RADII} for y in ECO_YEARS}
EMP = {y: {R: np.zeros(nST) for R in RADII} for y in ECO_YEARS}
for year in ECO_YEARS:
    codes, est, emp = _load_eco(year); M = _build_geom(pd.Series(codes))
    print(f"[{year}] {len(codes):,}メッシュ 事業所{int(est.sum()):,}/従業者{int(emp.sum()):,}（全国計＝公式民営確報と一致）")
    t0 = time.time()
    for j in range(nST):
        o = aggregate_radii_multi(M, {"e": est, "w": emp}, _sx[j], _sy[j])
        for R in RADII: EST[year][R][j] = o["e"][R]; EMP[year][R][j] = o["w"][R]
        if (j + 1) % 3000 == 0: print(f"  [{year}] {j+1}/{nST} ({time.time()-t0:.0f}s)")
    print(f"  [{year}] 集計完了 {time.time()-t0:.0f}s"); del M

# --- station_group へ付与（estab_/emp_ 接頭辞・水準→増減率→低分母フラグ。docs §6.3/§8） ---
_eco = {}; LV = {}
for VAR, D in [("estab", EST), ("emp", EMP)]:                                       # 水準: 事業所3年 → 従業者3年
    for year in [2021, 2016, 2012]:
        arr = np.rint(np.maximum.accumulate(np.column_stack([D[year][R] for R in RADII]), axis=1))  # 半径単調化→整数化
        LV[(VAR, year)] = arr
        for k, R in enumerate(RADII):
            _eco[f"{VAR}_n_{year}_{RNAME[R]}"] = pd.Series(arr[:, k], index=station_group.index).astype("Int64")
for VAR in ["estab", "emp"]:                                                        # 増減率: 9年(2012→21)・5年(2016→21)
    new = LV[(VAR, 2021)]
    for old in [2012, 2016]:
        base = LV[(VAR, old)]
        for k, R in enumerate(RADII):
            with np.errstate(divide="ignore", invalid="ignore"):
                g = np.where(base[:, k] > 0, (new[:, k] / base[:, k] - 1.0) * 100.0, np.nan)   # 分母0はNaN
            _eco[f"{VAR}_gr_2021_{old}_{RNAME[R]}"] = np.round(g, 1)
for k, R in enumerate(RADII):                                                       # 低分母フラグ（2012事業所<5・事業所/従業者の両増減率に共通）
    _eco[f"estab_gr_lown_{RNAME[R]}"] = (LV[("estab", 2012)][:, k] < 5).astype("int8")
station_group = pd.concat([station_group, pd.DataFrame(_eco, index=station_group.index)], axis=1)

_ecoc = [c for c in station_group.columns if c.startswith(("estab_", "emp_"))]
print(f"\n経済センサス列数: {len(_ecoc)}（水準36＝事業所/従業者×3年×6半径 ＋ 増減率24 ＋ 低分母フラグ6）")
# サニティ: 都心(多・従業者増) vs 地方(減)。docs §7.3 の実測と一致を確認
station_group[station_group["駅名"].isin(["東京", "大阪", "二月田", "つくば"])][
    ["駅名", "estab_n_2021_2km", "emp_n_2021_2km", "estab_gr_2021_2012_5km", "emp_gr_2021_2012_5km", "estab_gr_lown_500m"]]

[2021] 324,923メッシュ 事業所5,156,063/従業者57,949,915（全国計＝公式民営確報と一致）

  [2021] 3000/9273 (17s)

  [2021] 6000/9273 (34s)

  [2021] 9000/9273 (50s)

  [2021] 集計完了 52s

[2016] 321,398メッシュ 事業所5,340,783/従業者56,872,826（全国計＝公式民営確報と一致）

  [2016] 3000/9273 (17s)

  [2016] 6000/9273 (35s)

  [2016] 9000/9273 (51s)

  [2016] 集計完了 52s

[2012] 322,678メッシュ 事業所5,453,635/従業者55,837,252（全国計＝公式民営確報と一致）

  [2012] 3000/9273 (16s)

  [2012] 6000/9273 (33s)

  [2012] 9000/9273 (49s)

  [2012] 集計完了 51s

経済センサス列数: 66（水準36＝事業所/従業者×3年×6半径 ＋ 増減率24 ＋ 低分母フラグ6）

,駅名,estab_n_2021_2km,emp_n_2021_2km,estab_gr_2021_2012_5km,emp_gr_2021_2012_5km,estab_gr_lown_500m
95,つくば,1852,31572,6.7,15.6,0
982,二月田,679,5475,-10.9,-10.6,0
2956,大阪,35725,654082,-1.8,6.9,0
4933,東京,53617,1437269,2.8,15.4,0

## （14）所得（市町村税課税状況等の調 → 15〜64歳人口メッシュで駅×半径へ按分）

課税対象所得・納税義務者数は **市区町村単位でしか存在しない**（メッシュ・町丁字は非公表）。そこで
**半径円が市区町村 m の 15〜64歳人口の何割を含むか**を按分比率とし、市区町村の値を駅×半径へ配る
（方式A・docs/income.md §2）。総人口ではなく 15〜64歳人口を重みにするのは、納税義務者数の再現誤差が
中央値 13.9% → 5.1% に下がるため（docs/260805_research_add_dataset_economy.md §11.1）。

- 年度は **2015 / 2020 / 2025 年度**（値は前年の所得）。2024年度は定額減税で納税義務者が −303万人と異常なので採らない
- 重みは 2015年度→2015年国勢調査 ／ 2020・2025年度→2020年国勢調査（2025年調査のメッシュは未公表）
- 出力 72 列: `inc_pc`（万円/人）・`inc_total`（百万円）・`inc_gr`（%）・`inc_lown`（除外用）・`inc_city_only`（注意バッジ）

In [34]:
# （14）所得（市町村税課税状況等の調）→ 市区町村の課税対象所得・納税義務者数。docs/income.md 準拠
INCOME_DIR = BASE_DIR / "data" / "市町村税課税状況"
INCOME_YEARS = [2015, 2020, 2025]              # 課税年度（値は前年の所得）。pipeline/fetch_income.py が取得
INCOME_LATEST = max(INCOME_YEARS)
# 市制施行でコードが変わった団体は、古い年度に旧コードのまま載る。現行コードへ寄せないと
# 行政区域(N03)と結び付かず、その団体の所得が丸ごと落ちる（2015年度で 1,302億円＝未配分の 2/3）。
RENAMED_MUNI = {"04423": "04216", "40305": "40231"}   # 宮城県 富谷町→富谷市 / 福岡県 那珂川町→那珂川市
# 原表の全国計（特別区部 13100 は二重計上のため fetch_income.py が除外済み）
INCOME_TOTALS = {                              # 年度: (課税対象所得[千円], 納税義務者[人])
    2015: (183_717_970_493, 55_877_140),
    2020: (204_211_264_557, 59_398_579),
    2025: (241_047_499_326, 62_206_393),
}

def _load_income(year):
    """income_{年度}.csv → (所得[千円], 納税義務者[人], 団体名) の3つの dict（キー＝5桁コード）。"""
    df = pd.read_csv(INCOME_DIR / f"income_{year}.csv", dtype={"area_code": str})
    df["area_code"] = df["area_code"].map(lambda code: RENAMED_MUNI.get(code, code))
    g = df.groupby("area_code").agg(inc=("taxable_income_1000yen", "sum"), tax=("taxpayers", "sum"))
    return g["inc"].to_dict(), g["tax"].to_dict(), dict(zip(df["area_code"], df["area_name"]))

INCOME_MUNI = {year: _load_income(year) for year in INCOME_YEARS}
for year in INCOME_YEARS:
    inc, tax, _ = INCOME_MUNI[year]
    got = (int(sum(inc.values())), int(sum(tax.values())))
    assert got == INCOME_TOTALS[year], f"{year}年度の全国計が原表と不一致: {got}"
    print(f"[{year}年度] {len(inc):,}団体  課税対象所得 {got[0]/1e9:,.1f}兆円  納税義務者 {got[1]/1e4:,.0f}万人"
          f"  全国の1人当たり {got[0]/got[1]/10:,.1f}万円")

[2015年度] 1,741団体  課税対象所得 183.7兆円  納税義務者 5,588万人  全国の1人当たり 328.8万円
[2020年度] 1,741団体  課税対象所得 204.2兆円  納税義務者 5,940万人  全国の1人当たり 343.8万円
[2025年度] 1,741団体  課税対象所得 241.0兆円  納税義務者 6,221万人  全国の1人当たり 387.5万円

In [35]:
# 15〜64歳人口メッシュ(250m)に市区町村コードを付け、「半径内の15〜64歳人口の割合」で所得を按分する
WEIGHT_YEARS = {2015: 2015, 2020: 2020, 2025: 2020}          # 課税年度 → 重みに使う国勢調査年（2025年調査は未公表）
WORKING_AGE_CAT01 = 100                                       # 15〜64歳人口 総数（人口総数は 10）
WORKING_AGE_TOTALS = {2015: 76_288_736, 2020: 72_922_764}     # 国勢調査の公式全国計
N03_MUNI_SHP = f"zip://{N03_ZIP}!N03-20260101.shp"        # 市区町村版（セル（３）で都道府県版を読んだのと同じ zip）

def _load_n03_muni():
    """行政区域(N03) → (市区町村ポリゴン, 政令市の市計コード, 現行の全コード)。
    所得は市単位でしか無いので、政令市の行政区(N03_005 非空)は市計コードへ丸める（丸めないと政令市が穴になる）。"""
    name2code = {name: code for code, name in INCOME_MUNI[INCOME_LATEST][2].items()}
    poly = gpd.read_file(N03_MUNI_SHP, columns=["N03_001", "N03_004", "N03_005", "N03_007"])
    parent = (poly["N03_001"] + " " + poly["N03_004"]).map(name2code)          # "神奈川県 横浜市" → "14100"
    is_ward = poly["N03_005"].notna() & parent.notna()
    poly["muni"] = np.where(is_ward, parent, poly["N03_007"])
    poly["muni_raw"] = poly["N03_007"]        # 行政区はそのまま（§（15）売上は区別に取れる）
    return (poly[["muni", "muni_raw", "geometry"]], set(parent[is_ward]),
            set(poly["muni"].dropna()))

N03_POLY, SEIREI_CITY_CODES, N03_CODES = _load_n03_muni()
print(f"N03 {len(N03_POLY):,}ポリゴン → 市区町村 {len(N03_CODES):,}（うち政令市 {len(SEIREI_CITY_CODES)}）")

def _mesh_muni(M, code_col="muni"):
    """メッシュ中心点 → 5桁市区町村コード（Series）。海岸線の外に出た中心点は最近傍の市区町村へ寄せる。
    code_col="muni" は政令市を市計へ丸めた所得用、"muni_raw" は行政区のままの売上用（§（15））。"""
    pts = gpd.GeoDataFrame(geometry=gpd.points_from_xy(M["lon_c"], M["lat_c"]), crs="EPSG:6668")
    hit = gpd.sjoin(pts, N03_POLY, how="left", predicate="within")
    hit = hit[~hit.index.duplicated(keep="first")].reindex(pts.index)          # 境界の重なりは先勝ち
    miss = hit[code_col].isna().to_numpy()
    if miss.any():
        near = gpd.sjoin_nearest(pts[miss].to_crs(3857), N03_POLY.to_crs(3857), how="left")
        near = near[~near.index.duplicated(keep="first")]
        hit.loc[miss, code_col] = near[code_col].reindex(hit.index[miss]).to_numpy()
    return hit[code_col], int(miss.sum())

_sx, _sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy()); nST = len(station_group)
INC_ACC = {}
for wyear in sorted(set(WEIGHT_YEARS.values())):
    years = [y for y, w in WEIGHT_YEARS.items() if w == wyear]
    M = load_mesh_pop(BASE_DIR / "data" / f"国勢調査_人口及び世帯_{wyear}_mesh250",
                      pop_cat01=WORKING_AGE_CAT01, pattern="age1564_*.csv")
    assert M["total"] == WORKING_AGE_TOTALS[wyear], f"{wyear}年 15〜64歳人口の全国計が公式値と不一致: {M['total']:,}"
    muni, nmiss = _mesh_muni(M)
    pop = pd.Series(M["pop"]); denom = pop.groupby(muni).sum()                 # 市区町村ごとの15〜64歳人口＝按分の分母
    share = (pop / muni.map(denom)).fillna(0.0)                                # 人口0の団体は 0/0 → 0
    assert np.allclose(share.groupby(muni).sum()[denom > 0], 1.0), "按分比率の合計が1でない市区町村があります"
    print(f"[重み {wyear}年] {M['ncell']:,}セル / 15〜64歳 {M['total']:,}人 / 最近傍補完 {nmiss:,}セル / {len(denom):,}団体")

    vals = {}
    for year in years:
        inc, tax, name = INCOME_MUNI[year]
        unknown = sorted(set(inc) - N03_CODES)
        assert not unknown, f"{year}年度: 現行コードに無い団体 {[(c, name[c]) for c in unknown]} → RENAMED_MUNI に追加"
        vals[f"inc_{year}"] = (share * muni.map(inc)).fillna(0.0).to_numpy()   # 千円
        vals[f"tax_{year}"] = (share * muni.map(tax)).fillna(0.0).to_numpy()   # 人
        lost = {c: v for c, v in inc.items() if denom.get(c, 0.0) <= 0.0}      # 国勢調査人口0＝福島の避難区域
        print(f"  {year}年度 按分 {vals[f'inc_{year}'].sum()/1e9:,.2f}兆円 / 未配分 {sum(lost.values())/1e5:,.0f}億円"
              f"（{sum(lost.values())/sum(inc.values()):.4%}・{len(lost)}団体 {[name[c] for c in lost]}）")
    if INCOME_LATEST in years:                                                 # 政令市由来の納税者（注意バッジの分子）
        vals["tax_seirei"] = vals[f"tax_{INCOME_LATEST}"] * muni.isin(SEIREI_CITY_CODES).to_numpy()

    acc = {k: np.zeros((nST, len(RADII))) for k in vals}; t0 = time.time()
    for j in range(nST):
        o = aggregate_radii_multi(M, vals, _sx[j], _sy[j])
        for k in vals: acc[k][j] = [o[k][R] for R in RADII]
        if (j + 1) % 3000 == 0: print(f"  [重み {wyear}年] {j+1}/{nST} ({time.time()-t0:.0f}s)")
    INC_ACC.update(acc); print(f"  [重み {wyear}年] 集計完了 {time.time()-t0:.0f}s"); del M

N03 125,130ポリゴン → 市区町村 1,754（うち政令市 20）

[重み 2015年] 1,178,130セル / 15〜64歳 76,288,736人 / 最近傍補完 8,348セル / 1,738団体
  2015年度 按分 183.65兆円 / 未配分 665億円（0.0362%・5団体 ['福島県 富岡町', '福島県 大熊町', '福島県 双葉町', '福島県 浪江町', '福島県 飯舘村']）

  [重み 2015年] 3000/9273 (41s)

  [重み 2015年] 6000/9273 (101s)

  [重み 2015年] 9000/9273 (127s)

  [重み 2015年] 集計完了 129s

[重み 2020年] 1,163,757セル / 15〜64歳 72,922,764人 / 最近傍補完 8,252セル / 1,741団体
  2020年度 按分 204.20兆円 / 未配分 69億円（0.0034%・1団体 ['福島県 双葉町']）
  2025年度 按分 241.04兆円 / 未配分 67億円（0.0028%・1団体 ['福島県 双葉町']）

  [重み 2020年] 3000/9273 (29s)

  [重み 2020年] 6000/9273 (59s)

  [重み 2020年] 9000/9273 (87s)

  [重み 2020年] 集計完了 90s

In [36]:
# 半径単調化 → 1人当たり所得・総額・増減率・フラグを station_group へ付与（docs/income.md §4）
INCOME_PAIRS = [(2025, 2020), (2025, 2015)]   # 5年 / 10年
INC_LOWN_TAXPAYERS = 1000       # 半径内の納税義務者がこれ未満だと1人当たりが暴れる（猿払村 1,450人で752万円）
INC_CITY_ONLY_SHARE = 0.5       # 半径内の納税義務者の過半が政令市由来＝「市の平均」が主（除外ではなくバッジ）

_inc = {}; PC = {}; TAX = {}
for year in INCOME_YEARS:
    total_1000yen = np.maximum.accumulate(INC_ACC[f"inc_{year}"], axis=1)      # 単調化は総額のみ（float誤差対策）
    TAX[year] = np.maximum.accumulate(INC_ACC[f"tax_{year}"], axis=1)
    with np.errstate(divide="ignore", invalid="ignore"):
        pc = np.where(TAX[year] > 0, total_1000yen / TAX[year] / 10.0, np.nan)  # 千円/人 → 万円/人。分母0はNaN
    PC[year] = np.round(pc, 1)                                                  # 増減率は保存値から計算する
    for k, R in enumerate(RADII):
        _inc[f"inc_total_{year}_{RNAME[R]}"] = pd.Series(np.rint(total_1000yen[:, k] / 1000.0),
                                                         index=station_group.index).astype("Int64")   # 千円→百万円
        _inc[f"inc_pc_{year}_{RNAME[R]}"] = PC[year][:, k]
        _inc[f"inc_lown_{year}_{RNAME[R]}"] = (TAX[year][:, k] < INC_LOWN_TAXPAYERS).astype("int8")
for newer, older in INCOME_PAIRS:                                              # 1人当たりの増減率（%）
    for k, R in enumerate(RADII):
        with np.errstate(divide="ignore", invalid="ignore"):
            g = np.where(PC[older][:, k] > 0, (PC[newer][:, k] / PC[older][:, k] - 1.0) * 100.0, np.nan)
        _inc[f"inc_gr_{newer}_{older}_{RNAME[R]}"] = np.round(g, 1)
_seirei = np.maximum.accumulate(INC_ACC["tax_seirei"], axis=1)
for k, R in enumerate(RADII):
    with np.errstate(divide="ignore", invalid="ignore"):
        ratio = np.where(TAX[INCOME_LATEST][:, k] > 0, _seirei[:, k] / TAX[INCOME_LATEST][:, k], 0.0)
    _inc[f"inc_city_only_{RNAME[R]}"] = (ratio >= INC_CITY_ONLY_SHARE).astype("int8")
station_group = pd.concat([station_group, pd.DataFrame(_inc, index=station_group.index)], axis=1)   # 断片化回避
print(f"所得 列数: {len([c for c in station_group.columns if c.startswith('inc_')])}"
      f"（1人当たり18 ＋ 総額18 ＋ 増減率12 ＋ 低分母18 ＋ 政令市6 ＝ 72）")

所得 列数: 72（1人当たり18 ＋ 総額18 ＋ 増減率12 ＋ 低分母18 ＋ 政令市6 ＝ 72）

In [37]:
# 検証（docs/income.md §6）: 半径単調性・増減率の再計算一致・水準の妥当性・2つのフラグ
for year in INCOME_YEARS:
    lv = station_group[[f"inc_total_{year}_{RNAME[R]}" for R in RADII]].to_numpy(dtype="float64")
    assert (np.diff(lv, axis=1) >= 0).all(), f"inc_total_{year} が半径単調でない"
for newer, older in INCOME_PAIRS:
    for R in RADII:
        new = station_group[f"inc_pc_{newer}_{RNAME[R]}"].to_numpy(dtype="float64")
        old = station_group[f"inc_pc_{older}_{RNAME[R]}"].to_numpy(dtype="float64")
        with np.errstate(divide="ignore", invalid="ignore"):
            want = np.round(np.where(old > 0, (new / old - 1.0) * 100.0, np.nan), 1)
        got = station_group[f"inc_gr_{newer}_{older}_{RNAME[R]}"].to_numpy(dtype="float64")
        assert np.array_equal(want, got, equal_nan=True), f"inc_gr_{newer}_{older}_{RNAME[R]} が再計算と不一致"
print(f"半径単調性（inc_total 全{len(INCOME_YEARS)}年）・増減率の再計算一致（{len(INCOME_PAIRS)*len(RADII)}列）: OK")
print("政令市バッジ:  " + "  ".join(f"{RNAME[R]}={int(station_group[f'inc_city_only_{RNAME[R]}'].sum())}" for R in RADII))
print("低分母フラグ(2025): " + "  ".join(f"{RNAME[R]}={int(station_group[f'inc_lown_2025_{RNAME[R]}'].sum())}" for R in RADII))

_cols = ["駅名", "都道府県", "inc_pc_2025_1km", "inc_total_2025_1km", "inc_gr_2025_2015_1km", "inc_city_only_1km"]
print("\n1人当たり所得 上位10（1km・港区/渋谷区/千代田区の駅が並ぶはず）")
print(station_group.nlargest(10, "inc_pc_2025_1km")[_cols].to_string(index=False))
print("\n低分母フラグが立つ駅の1人当たり上位5（小さい分母で暴れている実例）")
print(station_group[station_group["inc_lown_2025_1km"] == 1].nlargest(5, "inc_pc_2025_1km")[
    ["駅名", "都道府県", "inc_pc_2025_1km", "inc_total_2025_1km", "inc_lown_2025_1km"]].to_string(index=False))
print("\nサニティ: 政令市の駅は inc_city_only=1／東京23区の駅は 0")
print(station_group[station_group["駅名"].isin(["横浜", "大阪", "東京", "渋谷", "二月田"])][
    ["駅名", "都道府県", "inc_pc_2025_1km", "inc_city_only_500m", "inc_city_only_1km", "inc_lown_2025_500m"]].to_string(index=False))

半径単調性（inc_total 全3年）・増減率の再計算一致（12列）: OK
政令市バッジ:  500m=1539  1km=1551  2km=1565  5km=1605  10km=1679  20km=1559
低分母フラグ(2025): 500m=4775  1km=2968  2km=1844  5km=627  10km=137  20km=8

1人当たり所得 上位10（1km・港区/渋谷区/千代田区の駅が並ぶはず）
  駅名 都道府県  inc_pc_2025_1km  inc_total_2025_1km  inc_gr_2025_2015_1km  inc_city_only_1km
  三田  東京都           1809.9              571328                  76.9                  0
 乃木坂  東京都           1809.9              376771                  76.9                  0
 六本木  東京都           1809.9              452407                  76.9                  0
 泉岳寺  東京都           1809.9              525981                  76.9                  0
  田町  東京都           1809.9              603738                  76.9                  0
白金高輪  東京都           1809.9              644033                  76.9                  0
 神谷町  東京都           1809.9              323434                  76.9                  0
 芝公園  東京都           1809.9              434507                  76.9                  0
芝浦ふ頭  東京都           1809.9              318972                  76.9                  0
 赤羽橋  東京都           1809.9              535714                  76.9                  0

低分母フラグが立つ駅の1人当たり上位5（小さい分母で暴れている実例）
           駅名 都道府県  inc_pc_2025_1km  inc_total_2025_1km  inc_lown_2025_1km
          桜田門  東京都           1376.1               10113                  1
         二重橋前  東京都           1003.7                4888                  1
東京国際クルーズターミナル  東京都            651.8                5063                  1
         信濃追分  長野県            608.7                3170                  1
          軽井沢  長野県            608.7                4118                  1

サニティ: 政令市の駅は inc_city_only=1／東京23区の駅は 0
 駅名 都道府県  inc_pc_2025_1km  inc_city_only_500m  inc_city_only_1km  inc_lown_2025_500m
二月田 鹿児島県            273.4                   0                  0                   1
 大阪  大阪府            398.0                   1                  1                   0
 東京  東京都            921.3                   0                  0                   1
 横浜 神奈川県            463.7                   1                  1                   0
 渋谷  東京都           1383.7                   0                  0                   0

## （15）売上（経済センサス活動調査 → メッシュの産業別従業者 × 市区町村の1人当たり売上）

`docs/sales.md` 準拠。**駅を目的地としたときの経済規模**（小売 ＋ 飲食・宿泊 ＋ 娯楽ほか）を、
**500m メッシュの産業別従業者数 × その市区町村の従業者 1 人当たり売上**で駅×半径へ落とす（推計）。

売上は市区町村までしか公表されないので、メッシュの従業者数で 500m の解像度へ引き伸ばす。
係数の**分母はメッシュ由来**にする（売上表の従業者数はメッシュより 3〜12% 少なく、そのまま使うと
全国計が同じだけ過大になる）。素データは `pipeline/fetch_sales.py` / `fetch_industry_mesh.py` が取得済み。

| 業種 | 売上の出所（市区町村）| かける相手（メッシュ）| 補正 |
|---|---|---|---|
| 小売 | 事業活動別の小売業 | Ｉ 卸売業，小売業の従業者数 | 卸売を外す ／ 2021 は個人経営分を足す |
| 飲食・宿泊 | 産業大分類Ｍ | Ｍ 宿泊業，飲食サービス業 | なし（本所比 9.4% で健全）|
| 娯楽ほか | 産業大分類Ｎの 総数 − 本所 | Ｎ 生活関連サービス業，娯楽業 | 本社の一括計上を外す |

年は**調査年**（2016 / 2021）で、**売上は前年 1 年間**（2015 年 / 2020 年。2020 年はコロナ 1 年目）。

In [38]:
# （15）売上（経済センサス‑活動調査）→ 市区町村の業種別売上。docs/sales.md 準拠
SALES_DIR = BASE_DIR / "data" / "経済センサス_売上"
SALES_YEARS = [2016, 2021]                 # 調査年（売上は前年 1 年間＝2015年・2020年）
KIND_IND = {"retail": "i", "food": "m", "leisure": "n"}     # 業種 → メッシュの産業（Ｉ/Ｍ/Ｎ）
# 統計側と N03（2026-01-01 時点）でコードが食い違う団体を、共通のキーへ寄せる。
# 寄せないと浜松市の売上 1.1 兆円が丸ごと未配分になる（浜松市は 2024-01 に 7 区→3 区へ再編）。
MUNI_ALIAS = {"04423": "04216", "40305": "40231"}           # 富谷町→富谷市 / 那珂川町→那珂川市
MUNI_ALIAS.update({c: "22130" for c in                       # 浜松市：旧7区（統計）・新3区（N03）とも市計へ
                   ["22131", "22132", "22133", "22134", "22135", "22136", "22137",
                    "22138", "22139", "22140"]})
SALES_TOTALS = {                            # pipeline/fetch_sales.py が検証済みの市区町村計（百万円）
    2016: {"retail": 146_134_162, "food": 23_882_959, "leisure": 38_854_929},
    2021: {"retail": 146_227_527, "food": 19_037_095, "leisure": 23_680_841},
}

def _load_sales(year):
    """sales_{年}.csv → {業種: {市区町村コード: 売上(百万円)}}。秘匿は 0 にせず入れない。"""
    df = pd.read_csv(SALES_DIR / f"sales_{year}.csv", dtype={"area_code": str})
    df["area_code"] = df["area_code"].map(lambda code: MUNI_ALIAS.get(code, code))
    return {kind: df.dropna(subset=[f"{kind}_million_yen"])
                    .groupby("area_code")[f"{kind}_million_yen"].sum().to_dict()
            for kind in KIND_IND}

SALES_MUNI = {year: _load_sales(year) for year in SALES_YEARS}
for year in SALES_YEARS:
    got = {kind: round(sum(v.values())) for kind, v in SALES_MUNI[year].items()}
    assert got == SALES_TOTALS[year], f"{year}年の市区町村計が取得時の検証値と不一致: {got}"
    print(f"[{year}年調査] 小売 {got['retail']/1e6:5.1f}兆円 / 飲食・宿泊 {got['food']/1e6:5.1f}兆円"
          f" / 娯楽ほか {got['leisure']/1e6:5.1f}兆円  （売上は前年 1 年間・{len(SALES_MUNI[year]['retail']):,}団体）")

[2016年調査] 小売 146.1兆円 / 飲食・宿泊  23.9兆円 / 娯楽ほか  38.9兆円  （売上は前年 1 年間・1,881団体）
[2021年調査] 小売 146.2兆円 / 飲食・宿泊  19.0兆円 / 娯楽ほか  23.7兆円  （売上は前年 1 年間・1,823団体）

In [39]:
# メッシュの産業別従業者数 × 市区町村の係数（＝売上 ÷ メッシュ由来の従業者数）で駅×半径へ按分
SALES_MESH_2021 = {"i": "T001162032", "m": "T001162036", "n": "T001162037"}   # 2021 生zip の従業者数列
IND_DIR_2016 = ECO_DIR / "2016_industry"    # pipeline/fetch_industry_mesh.py が取得（2016 は総数しか無かった）

def _load_eco_industry(year):
    """500m メッシュの産業別従業者数（Ｉ/Ｍ/Ｎ）。2021＝生zipの列／2016＝取得済みCSV。"""
    codes = []; emp = {ind: [] for ind in ("i", "m", "n")}
    if year == 2021:
        for zp in sorted(glob.glob(str(ECO_DIR / "2021" / "tblT001162H*.zip"))):
            with zipfile.ZipFile(zp) as z: txt = z.read(z.namelist()[0]).decode("shift_jis")
            df = pd.read_csv(io.StringIO(txt), dtype=str)
            df = df[df["KEY_CODE"].str.match(r"^\d+$", na=False)]
            codes.append(df["KEY_CODE"].to_numpy())
            for ind, col in SALES_MESH_2021.items():
                emp[ind].append(pd.to_numeric(df[col], errors="coerce").fillna(0).to_numpy())
    else:
        for fp in sorted(glob.glob(str(IND_DIR_2016 / f"eco{year}ind_*.csv"))):
            df = pd.read_csv(fp, dtype={"KEY_CODE": str})
            codes.append(df["KEY_CODE"].to_numpy())
            for ind in emp:
                emp[ind].append(pd.to_numeric(df[f"emp_{ind}"], errors="coerce").fillna(0).to_numpy())
    return np.concatenate(codes), {ind: np.concatenate(v).astype(float) for ind, v in emp.items()}

_sx, _sy = tf_aea.transform(station_group["lon"].to_numpy(), station_group["lat"].to_numpy()); nST = len(station_group)
SALES_ACC = {}
for year in SALES_YEARS:
    codes, emp = _load_eco_industry(year); M = _build_geom(pd.Series(codes))
    muni, nmiss = _mesh_muni(M, "muni_raw")          # 行政区はそのまま（所得と違い売上は区別に取れる）
    muni = muni.map(lambda code: MUNI_ALIAS.get(code, code) if isinstance(code, str) else code)
    print(f"[{year}年] {len(codes):,}メッシュ  Ｉ{emp['i'].sum():,.0f} / Ｍ{emp['m'].sum():,.0f}"
          f" / Ｎ{emp['n'].sum():,.0f}人  最近傍補完 {nmiss:,}セル")
    vals = {f"emp_{ind}": emp[ind] for ind in ("i", "m", "n")}
    for kind, ind in KIND_IND.items():
        denom = pd.Series(emp[ind]).groupby(muni).sum()          # 分母＝メッシュ由来（docs/sales.md §2.3）
        coef = {code: sales / denom[code] for code, sales in SALES_MUNI[year][kind].items()
                if code in denom.index and denom[code] > 0}
        vals[kind] = emp[ind] * muni.map(coef).fillna(0.0).to_numpy()
        want = sum(SALES_MUNI[year][kind][code] for code in coef)
        assert np.isclose(vals[kind].sum(), want, rtol=1e-9), f"{year}年 {kind}: 按分の保存則が崩れた"
        lost = {code: s for code, s in SALES_MUNI[year][kind].items() if code not in coef}
        print(f"  {kind:8s} 係数 {len(coef):,}団体  配分 {vals[kind].sum()/1e6:6.2f}兆円"
              f"  未配分 {sum(lost.values())/1e6:.3f}兆円（{sum(lost.values())/max(want,1):.3%}・{list(lost)[:2]}）")

    acc = {key: np.zeros((nST, len(RADII))) for key in vals}; t0 = time.time()
    for j in range(nST):
        o = aggregate_radii_multi(M, vals, _sx[j], _sy[j])
        for key in vals: acc[key][j] = [o[key][R] for R in RADII]
        if (j + 1) % 3000 == 0: print(f"  [{year}年] {j+1}/{nST} ({time.time()-t0:.0f}s)")
    SALES_ACC[year] = acc; print(f"  [{year}年] 集計完了 {time.time()-t0:.0f}s"); del M

[2016年] 217,974メッシュ  Ｉ11,843,869 / Ｍ5,362,088 / Ｎ2,420,557人  最近傍補完 4,268セル
  retail   係数 1,880団体  配分 146.09兆円  未配分 0.044兆円（0.030%・['13199']）
  food     係数 1,878団体  配分  23.87兆円  未配分 0.017兆円（0.070%・['13199']）
  leisure  係数 1,856団体  配分  38.85兆円  未配分 0.008兆円（0.020%・['13199']）

  [2016年] 3000/9273 (13s)

  [2016年] 6000/9273 (27s)

  [2016年] 9000/9273 (55s)

  [2016年] 集計完了 56s

[2021年] 324,923メッシュ  Ｉ11,612,174 / Ｍ4,701,797 / Ｎ2,195,981人  最近傍補完 6,261セル
  retail   係数 1,822団体  配分 146.21兆円  未配分 0.016兆円（0.011%・['13199']）
  food     係数 1,876団体  配分  19.02兆円  未配分 0.012兆円（0.064%・['13199']）
  leisure  係数 1,855団体  配分  23.67兆円  未配分 0.006兆円（0.025%・['13199']）

  [2021年] 3000/9273 (17s)

  [2021年] 6000/9273 (34s)

  [2021年] 9000/9273 (50s)

  [2021年] 集計完了 52s

In [40]:
# 半径単調化 → 億円へ丸め → 売上・産業別従業者数・増減率・低分母フラグを station_group へ付与
SALES_PAIR = (2021, 2016)      # 増減率（5年）
SALES_LOWN_EMP = 50            # 半径内の対象従業者がこれ未満だと増減率が暴れる（下のセルで実測して決めた）
EMP_NAME = {"i": "trade", "m": "food", "n": "life"}   # 列名：卸売・小売／宿泊・飲食／生活関連・娯楽

_sales = {}; DEST = {}; EMP_TOTAL = {}
for year in SALES_YEARS:
    dest = np.zeros((nST, len(RADII)))
    for kind in KIND_IND:                                   # 売上は億円・小数1桁。合計は丸める前の値から作る
        arr = np.maximum.accumulate(SALES_ACC[year][kind], axis=1)   # 面積按分の和なので半径に単調
        dest += arr
        for k, R in enumerate(RADII):
            _sales[f"sales_{kind}_{year}_{RNAME[R]}"] = np.round(arr[:, k] / 100.0, 1)
    DEST[year] = np.round(dest / 100.0, 1)
    emp_total = np.zeros((nST, len(RADII)))
    for ind, name in EMP_NAME.items():                      # 産業別の従業者数（実測・整数）
        arr = np.rint(np.maximum.accumulate(SALES_ACC[year][f"emp_{ind}"], axis=1))
        emp_total += arr
        for k, R in enumerate(RADII):
            _sales[f"emp_{name}_n_{year}_{RNAME[R]}"] = pd.Series(arr[:, k], index=station_group.index).astype("Int64")
    EMP_TOTAL[year] = emp_total
    for k, R in enumerate(RADII):
        _sales[f"sales_dest_{year}_{RNAME[R]}"] = DEST[year][:, k]
        _sales[f"sales_lown_{year}_{RNAME[R]}"] = (emp_total[:, k] < SALES_LOWN_EMP).astype("int8")

_new, _old = SALES_PAIR                                      # 増減率は保存値から再計算する（%）
for k, R in enumerate(RADII):
    with np.errstate(divide="ignore", invalid="ignore"):
        _sales[f"sales_dest_gr_{_new}_{_old}_{RNAME[R]}"] = np.round(np.where(
            DEST[_old][:, k] > 0, (DEST[_new][:, k] / DEST[_old][:, k] - 1) * 100.0, np.nan), 1)
        _sales[f"emp_dest_gr_{_new}_{_old}_{RNAME[R]}"] = np.round(np.where(
            EMP_TOTAL[_old][:, k] > 0, (EMP_TOTAL[_new][:, k] / EMP_TOTAL[_old][:, k] - 1) * 100.0, np.nan), 1)
for ind, name in EMP_NAME.items():
    for k, R in enumerate(RADII):
        base = _sales[f"emp_{name}_n_{_old}_{RNAME[R]}"].to_numpy(dtype=float)
        now = _sales[f"emp_{name}_n_{_new}_{RNAME[R]}"].to_numpy(dtype=float)
        with np.errstate(divide="ignore", invalid="ignore"):
            _sales[f"emp_{name}_gr_{_new}_{_old}_{RNAME[R]}"] = np.round(
                np.where(base > 0, (now / base - 1) * 100.0, np.nan), 1)
station_group = pd.concat([station_group, pd.DataFrame(_sales, index=station_group.index)], axis=1)   # 断片化回避
_scols = [c for c in station_group.columns
          if c.startswith(("sales_", "emp_trade", "emp_food", "emp_life", "emp_dest"))]
print(f"売上 列数: {len(_scols)}（売上 48 ＋ 産業別従業者 36 ＋ 増減率 30 ＋ 低分母 12 ＝ 126）")

売上 列数: 126（売上 48 ＋ 産業別従業者 36 ＋ 増減率 30 ＋ 低分母 12 ＝ 126）

In [41]:
# 検証（docs/sales.md §6）: 半径単調性・増減率の再計算一致・水準の妥当性・低分母フラグの根拠
_mono = [c for c in _scols if c.startswith(("sales_retail", "sales_food", "sales_leisure", "sales_dest_2",
                                            "emp_trade_n", "emp_food_n", "emp_life_n"))]
_bad = 0
for base in sorted({c.rsplit("_", 1)[0] for c in _mono}):
    arr = station_group[[f"{base}_{RNAME[R]}" for R in RADII]].to_numpy(dtype=float)
    _bad += int((np.diff(arr, axis=1) < -1e-6).sum())
def _regr_bad(base, now, col):     # 格納した水準から増減率を再計算し、格納した増減率と突き合わせる
    with np.errstate(divide="ignore", invalid="ignore"):
        want = np.round(np.where(base > 0, (now / base - 1) * 100.0, np.nan), 1)
    return int((~np.isclose(want, station_group[col].to_numpy(dtype=float), equal_nan=True)).sum())

def _col(prefix, year, R):
    return station_group[f"{prefix}_{year}_{RNAME[R]}"].to_numpy(dtype=float)

_regr = 0
for R in RADII:
    _regr += _regr_bad(_col("sales_dest", 2016, R), _col("sales_dest", 2021, R),
                       f"sales_dest_gr_2021_2016_{RNAME[R]}")
    _emp = {y: sum(_col(f"emp_{n}_n", y, R) for n in EMP_NAME.values()) for y in SALES_YEARS}
    _regr += _regr_bad(_emp[2016], _emp[2021], f"emp_dest_gr_2021_2016_{RNAME[R]}")
    for name in EMP_NAME.values():
        _regr += _regr_bad(_col(f"emp_{name}_n", 2016, R), _col(f"emp_{name}_n", 2021, R),
                           f"emp_{name}_gr_2021_2016_{RNAME[R]}")
print(f"半径単調性（売上4系列×2年 ＋ 産業別従業者3系列×2年）: {'OK' if _bad == 0 else f'NG {_bad}件'}"
      f" ／ 増減率の再計算一致（30列）: {'OK' if _regr == 0 else f'NG {_regr}件'}")
print("低分母フラグ(2016):", "  ".join(
    f"{RNAME[R]}={int(station_group[f'sales_lown_2016_{RNAME[R]}'].sum())}" for R in RADII))

print("\n目的地としての売上 上位10（1km・億円）")
_top = station_group.nlargest(10, "sales_dest_2021_1km")[
    ["駅名", "都道府県", "sales_dest_2021_1km", "sales_retail_2021_1km", "sales_food_2021_1km",
     "sales_leisure_2021_1km", "sales_dest_gr_2021_2016_1km", "emp_dest_gr_2021_2016_1km"]]
print(_top.to_string(index=False))

print("\n代表駅（1km・億円）― 熱海は飲食・宿泊＞小売になるはず（観光地の性格）")
_spot = station_group[station_group["grp"].isin(["吉祥寺#0", "熱海#0", "稚内#0", "銀座#0", "日本橋#0"])][
    ["駅名", "都道府県", "sales_dest_2016_1km", "sales_dest_2021_1km", "sales_retail_2021_1km",
     "sales_food_2021_1km", "sales_leisure_2021_1km", "sales_dest_gr_2021_2016_1km"]]
print(_spot.to_string(index=False))

print("\n低分母フラグの根拠：2016 の対象従業者数の帯ごとに、目的地計の増減率がどれだけ暴れるか（1km）")
_base = EMP_TOTAL[2016][:, RADII.index(1000)]
_gr = station_group["sales_dest_gr_2021_2016_1km"].to_numpy(dtype=float)
for lo, hi in [(0, 20), (20, 50), (50, 100), (100, 500), (500, 10**9)]:
    sel = (~np.isnan(_gr)) & (_base >= lo) & (_base < hi)
    if sel.sum():
        v = np.sort(_gr[sel])
        print(f"  従業者 {lo:5d}〜{hi if hi < 10**8 else '':>5}人: {sel.sum():5d}駅  "
              f"中央値 {np.median(v):+7.1f}%  5%点 {v[int(len(v)*0.05)]:+8.1f}%  95%点 {v[int(len(v)*0.95)]:+8.1f}%")

半径単調性（売上4系列×2年 ＋ 産業別従業者3系列×2年）: OK ／ 増減率の再計算一致（30列）: OK
低分母フラグ(2016): 500m=2389  1km=1423  2km=732  5km=162  10km=19  20km=0

目的地としての売上 上位10（1km・億円）
  駅名 都道府県  sales_dest_2021_1km  sales_retail_2021_1km  sales_food_2021_1km  sales_leisure_2021_1km  sales_dest_gr_2021_2016_1km  emp_dest_gr_2021_2016_1km
 日本橋  東京都              12170.3                 9886.0               1685.2                   599.2                        -15.3                        2.2
 三越前  東京都              11903.4                 9649.1               1679.0                   575.3                        -14.1                        6.0
 東梅田  大阪府              11760.1                 6482.0               3595.9                  1682.2                        -27.5                       -7.9
 北新地  大阪府              11722.9                 6806.1               3305.7                  1611.1                        -27.0                       -7.9
  京橋  東京都              11486.7                 8666.0               1966.6                   854.1                        -24.3                       -0.9
 西梅田  大阪府              11372.7                 6594.9               3224.5                  1553.3                        -26.8                       -7.6
  新宿  東京都              11185.5                 8035.9               1622.6                  1526.9                        -28.2                      -17.3
  宝町  東京都              11178.1                 8589.2               1785.9                   803.0                        -24.3                       -2.9
新宿西口  東京都              11055.6                 7907.7               1644.3                  1503.6                        -29.4                      -17.0
新日本橋  東京都              10999.5                 8918.8               1484.0                   596.8                        -16.9                        4.8

代表駅（1km・億円）― 熱海は飲食・宿泊＞小売になるはず（観光地の性格）
 駅名 都道府県  sales_dest_2016_1km  sales_dest_2021_1km  sales_retail_2021_1km  sales_food_2021_1km  sales_leisure_2021_1km  sales_dest_gr_2021_2016_1km
吉祥寺  東京都               2591.9               1902.3                 1469.2                263.3                   169.9                        -26.6
日本橋  大阪府               8862.3               7670.4                 3233.3               1201.6                  3235.6                        -13.4
 熱海  静岡県                286.2                221.1                   86.8                124.0                    10.4                        -22.7
 稚内  北海道                171.7                132.6                  102.7                 13.0                    16.9                        -22.8
 銀座  東京都              14285.3               9802.8                 6331.3               2487.3                   984.2                        -31.4

低分母フラグの根拠：2016 の対象従業者数の帯ごとに、目的地計の増減率がどれだけ暴れるか（1km）
  従業者     0〜   20人:   696駅  中央値   -15.8%  5%点   -100.0%  95%点   +250.0%
  従業者    20〜   50人:   551駅  中央値   -16.7%  5%点    -67.2%  95%点    +57.7%
  従業者    50〜  100人:   622駅  中央値   -14.4%  5%点    -51.6%  95%点    +44.8%
  従業者   100〜  500人:  1892駅  中央値    -8.6%  5%点    -39.0%  95%点    +29.2%
  従業者   500〜     人:  5336駅  中央値   -10.2%  5%点    -29.9%  95%点    +16.3%

In [42]:
# CSV 出力: DB(Supabase/PostGIS)取込を見据えた最終成果物。
#   - lon/lat を保持（geometry は取込時に ST_SetSRID(ST_MakePoint(lon,lat),4326) で生成）。
#   - 日本語の列【名】を ASCII snake_case に変換（値は日本語のまま）→ PostgREST/API・SQLで扱いやすい。
OUT_DIR = BASE_DIR / "data" / "derived"
OUT_DIR.mkdir(parents=True, exist_ok=True)
COLMAP = {"駅名": "station_name", "都道府県": "prefecture", "運営会社": "operator"}  # rename は該当列のみ適用

# メイン: 1群1行 × 全データ（乗降客・人口実績/将来推計/増減率/予測誤差/信頼性フラグ）
station_dataset = station_group.rename(columns=COLMAP)
station_dataset.to_csv(OUT_DIR / "station_dataset.csv", index=False)

# 監査明細: 1群×1社の素データ（各年値・在/欠測・参照年）。検証・トレース用
station_operator_detail = station_group_operator.rename(columns=COLMAP)
station_operator_detail.to_csv(OUT_DIR / "station_operator_detail.csv", index=False)

# 地価 各年水準パネル（グラフ用・ロング形式。station_dataset とは grp で結合）
lp_panel.to_csv(OUT_DIR / "station_landprice_yearly.csv", index=False)

# 路線（1群×1社×1路線）。S12 の各レコードは grp を付与済み（セル「空間グループ」）なので、
# **駅グループとの対応づけは構成上そのまま**（従来 pipeline/build_station_routes.py が
# 最近傍距離で貼り直していた工程が不要になる）。route_type は S12_005 の事業者種別コード。
station_routes = (gdf[["grp", "運営会社", "路線名", "事業者種別"]]
                  .rename(columns={"運営会社": "operator", "路線名": "route", "事業者種別": "route_type"})
                  .astype({"route_type": int})
                  .drop_duplicates()
                  .sort_values(["grp", "operator", "route", "route_type"], kind="stable"))
station_routes.to_csv(OUT_DIR / "station_routes.csv", index=False)

_na_main = [c for c in station_dataset.columns if not c.isascii()]
_na_det  = [c for c in station_operator_detail.columns if not c.isascii()]
print("saved:")
print(f"  メインデータセット : {OUT_DIR/'station_dataset.csv'}  {station_dataset.shape}")
print(f"  監査明細(1群×1社)  : {OUT_DIR/'station_operator_detail.csv'}  {station_operator_detail.shape}")
print(f"  地価 各年水準パネル: {OUT_DIR/'station_landprice_yearly.csv'}  {lp_panel.shape}")
print(f"  路線（1群×1社×1路線）: {OUT_DIR/'station_routes.csv'}  {station_routes.shape}"
      f"  路線が付いた駅グループ {station_routes['grp'].nunique()}/{len(station_group)}")
print(f"  ASCII化した列名     : {COLMAP}")
print(f"  残存する非ASCII列名 : main={_na_main} / detail={_na_det}（期待: 両方 []）")

saved:
  メインデータセット : /Users/kensuke26/Developer/AI-Database-Map/data/derived/station_dataset.csv  (9273, 794)
  監査明細(1群×1社)  : /Users/kensuke26/Developer/AI-Database-Map/data/derived/station_operator_detail.csv  (9781, 32)
  地価 各年水準パネル: /Users/kensuke26/Developer/AI-Database-Map/data/derived/station_landprice_yearly.csv  (674105, 5)
  路線（1群×1社×1路線）: /Users/kensuke26/Developer/AI-Database-Map/data/derived/station_routes.csv  (10424, 4)  路線が付いた駅グループ 9273/9273
  ASCII化した列名     : {'駅名': 'station_name', '都道府県': 'prefecture', '運営会社': 'operator'}
  残存する非ASCII列名 : main=[] / detail=[]（期待: 両方 []）